// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ReadMode selects which slice of the stored content a read returns.
 * @readonly
 * @enum {string}
 */
export const ReadMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ModeHead: "head",
    ModeTail: "tail",
    ModeRange: "range",
    ModeSearch: "search",

    /**
     * bounded: capped at MaxHandleChars units
     */
    ModeFull: "full",
};

/**
 * ReadOptions selects the slice to return.
 */
export class ReadOptions {
    /**
     * Creates a new ReadOptions instance.
     * @param {Partial<ReadOptions>} [$$source = {}] - The source object to create the ReadOptions.
     */
    constructor($$source = {}) {
        if (!("HandleID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["HandleID"] = "";
        }
        if (!("ChatSessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ChatSessionID"] = "";
        }
        if (!("Mode" in $$source)) {
            /**
             * @member
             * @type {ReadMode}
             */
            this["Mode"] = ReadMode.$zero;
        }
        if (!("Offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Offset"] = 0;
        }
        if (!("MaxChars" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["MaxChars"] = 0;
        }
        if (!("Query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReadOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadOptions(/** @type {Partial<ReadOptions>} */($$parsedSource));
    }
}

/**
 * StoreInputResult reports what was retained.
 */
export class StoreInputResult {
    /**
     * Creates a new StoreInputResult instance.
     * @param {Partial<StoreInputResult>} [$$source = {}] - The source object to create the StoreInputResult.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("ChatSessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ChatSessionID"] = "";
        }
        if (!("TotalUnits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TotalUnits"] = 0;
        }
        if (!("StoredUnits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["StoredUnits"] = 0;
        }
        if (!("SourceTruncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["SourceTruncated"] = false;
        }
        if (!("Preview" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Preview"] = "";
        }
        if (!("SpillPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SpillPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StoreInputResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StoreInputResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StoreInputResult(/** @type {Partial<StoreInputResult>} */($$parsedSource));
    }
}
