// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppendResult {
    /**
     * Creates a new AppendResult instance.
     * @param {Partial<AppendResult>} [$$source = {}] - The source object to create the AppendResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["stopped"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Step[] | undefined}
             */
            this["steps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["code"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppendResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppendResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField4_0($$parsedSource["steps"]);
        }
        return new AppendResult(/** @type {Partial<AppendResult>} */($$parsedSource));
    }
}

/**
 * Step is one recorded script action.
 */
export class Step {
    /**
     * Creates a new Step instance.
     * @param {Partial<Step>} [$$source = {}] - The source object to create the Step.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["timeoutMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["sensitive"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Step instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Step}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Step(/** @type {Partial<Step>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Step.createFrom;
const $$createType1 = $Create.Array($$createType0);
