// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppendResult {
    /**
     * Creates a new AppendResult instance.
     * @param {Partial<AppendResult>} [$$source = {}] - The source object to create the AppendResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["stopped"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Step[] | undefined}
             */
            this["steps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["code"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppendResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppendResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField4_0($$parsedSource["steps"]);
        }
        return new AppendResult(/** @type {Partial<AppendResult>} */($$parsedSource));
    }
}

export class Run {
    /**
     * Creates a new Run instance.
     * @param {Partial<Run>} [$$source = {}] - The source object to create the Run.
     */
    constructor($$source = {}) {
        if (!("runId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["scriptId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["scriptLabel"] = undefined;
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAt"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["endedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {RunLog[]}
             */
            this["logs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Run instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Run}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField8_0($$parsedSource["logs"]);
        }
        return new Run(/** @type {Partial<Run>} */($$parsedSource));
    }
}

export class RunLog {
    /**
     * Creates a new RunLog instance.
     * @param {Partial<RunLog>} [$$source = {}] - The source object to create the RunLog.
     */
    constructor($$source = {}) {
        if (!("at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["at"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunLog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunLog}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunLog(/** @type {Partial<RunLog>} */($$parsedSource));
    }
}

/**
 * Step is one recorded script action.
 */
export class Step {
    /**
     * Creates a new Step instance.
     * @param {Partial<Step>} [$$source = {}] - The source object to create the Step.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["timeoutMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["sensitive"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Step instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Step}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Step(/** @type {Partial<Step>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Step.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RunLog.createFrom;
const $$createType3 = $Create.Array($$createType2);
