// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService is the Wails-facing facade of the Go turn runtime (W12,
 * P7-04, AI-03). It is a thin mapping: the runtime owns all invariants,
 * the React client owns no second authoritative state. The five methods
 * mirror the W03 wire DTOs one to one.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "../../internal/agent/tools/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../../internal/app/contracts/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AgentPendingInteractions lists open approval prompts for the settings UI.
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function AgentPendingInteractions() {
    return $Call.ByID(689829149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AgentPrepare reserves one turn slot. Idempotent per request ID.
 * @param {contracts$0.PrepareTurnRequest} request
 * @returns {$CancellablePromise<contracts$0.PreparedTurn>}
 */
export function AgentPrepare(request) {
    return $Call.ByID(3172602556, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * AgentReadEvents pages turn events after a decimal-string cursor.
 * @param {string} turnID
 * @param {string} afterSequence
 * @param {number} limit
 * @returns {$CancellablePromise<contracts$0.EventPage>}
 */
export function AgentReadEvents(turnID, afterSequence, limit) {
    return $Call.ByID(4134149572, turnID, afterSequence, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * AgentRegisterChatAttachments lets the renderer push the current chat's
 * attachments into the host registry so agents can list/read them.
 * @param {string} chatSessionID
 * @param {$models.Attachment[]} attachments
 * @returns {$CancellablePromise<void>}
 */
export function AgentRegisterChatAttachments(chatSessionID, attachments) {
    return $Call.ByID(3332714496, chatSessionID, attachments);
}

/**
 * AgentRespondInteraction resolves one pending approval. The decision is
 * consumed exactly once; unknown or stale IDs fail typed.
 * @param {string} interactionID
 * @param {boolean} approved
 * @returns {$CancellablePromise<void>}
 */
export function AgentRespondInteraction(interactionID, approved) {
    return $Call.ByID(2580188558, interactionID, approved);
}

/**
 * AgentSnapshot returns the authoritative turn projection.
 * @param {string} turnID
 * @returns {$CancellablePromise<contracts$0.TurnSnapshot>}
 */
export function AgentSnapshot(turnID) {
    return $Call.ByID(1938931437, turnID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * AgentStart starts a prepared turn. Idempotent retries never re-run the
 * driver.
 * @param {contracts$0.TurnCommand} command
 * @returns {$CancellablePromise<void>}
 */
export function AgentStart(command) {
    return $Call.ByID(1992686271, command);
}

/**
 * AgentStatus reports runtime readiness. Without the dev flag the Go
 * runtime has no provider behind it, so the renderer must keep using its
 * own chain until the live provider wiring lands (W13+).
 * @returns {$CancellablePromise<$models.AgentStatus>}
 */
export function AgentStatus() {
    return $Call.ByID(2395112271).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * AgentStop converges one turn and returns its terminal snapshot.
 * @param {string} turnID
 * @param {string} reason
 * @returns {$CancellablePromise<contracts$0.TurnSnapshot>}
 */
export function AgentStop(turnID, reason) {
    return $Call.ByID(3522632773, turnID, reason).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ToolOutputRead implements harness.tool_output.read over the W14 handle
 * store: bounded head/tail/range/full/search reads with owner chat scope
 * and explicit expired/not-found/evicted outcomes.
 * @param {string} chatSessionID
 * @param {tools$0.ReadOptions} input
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ToolOutputRead(chatSessionID, input) {
    return $Call.ByID(2518588099, chatSessionID, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ToolOutputStore stores tool output under a fresh handle.
 * @param {string} chatSessionID
 * @param {string} capabilityID
 * @param {string} sessionID
 * @param {string} content
 * @param {number} previewChars
 * @returns {$CancellablePromise<tools$0.StoreInputResult>}
 */
export function ToolOutputStore(chatSessionID, capabilityID, sessionID, content, previewChars) {
    return $Call.ByID(1794602232, chatSessionID, capabilityID, sessionID, content, previewChars).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = contracts$0.PreparedTurn.createFrom;
const $$createType3 = contracts$0.EventPage.createFrom;
const $$createType4 = contracts$0.TurnSnapshot.createFrom;
const $$createType5 = $models.AgentStatus.createFrom;
const $$createType6 = tools$0.StoreInputResult.createFrom;
