// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.CodexLoginResult>}
 */
export function CodexCancelLogin(sessionID) {
    return $Call.ByID(2925650086, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.CodexIntegrationOptions} options
 * @returns {$CancellablePromise<$models.CodexIntegrationStatus>}
 */
export function CodexGetIntegration(options) {
    return $Call.ByID(2122397961, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.CodexLoginResult>}
 */
export function CodexGetLoginSession(sessionID) {
    return $Call.ByID(675606730, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.CodexIntegrationOptions} options
 * @returns {$CancellablePromise<$models.CodexLogoutResult>}
 */
export function CodexLogout(options) {
    return $Call.ByID(3838627337, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.CodexIntegrationOptions} options
 * @returns {$CancellablePromise<$models.CodexLoginResult>}
 */
export function CodexStartLogin(options) {
    return $Call.ByID(2887084730, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {boolean} refreshShellEnv
 * @param {boolean} apiKeyPresent
 * @returns {$CancellablePromise<$models.DiscoveredAgentCLI[]>}
 */
export function Discover(refreshShellEnv, apiKeyPresent) {
    return $Call.ByID(1078283503, refreshShellEnv, apiKeyPresent).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AgentCLIPrewarmResult>}
 */
export function Prewarm() {
    return $Call.ByID(853984860).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} command
 * @param {string} customPath
 * @param {boolean} refreshShellEnv
 * @param {boolean} apiKeyPresent
 * @returns {$CancellablePromise<$models.AgentCLIPathInfo>}
 */
export function Resolve(command, customPath, refreshShellEnv, apiKeyPresent) {
    return $Call.ByID(2334403244, command, customPath, refreshShellEnv, apiKeyPresent).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CodexLoginResult.createFrom;
const $$createType1 = $models.CodexIntegrationStatus.createFrom;
const $$createType2 = $models.CodexLogoutResult.createFrom;
const $$createType3 = $models.DiscoveredAgentCLI.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.AgentCLIPrewarmResult.createFrom;
const $$createType6 = $models.AgentCLIPathInfo.createFrom;
