// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService is the Wails-facing facade of the Go turn runtime (W12,
 * P7-04, AI-03). It is a thin mapping: the runtime owns all invariants,
 * the React client owns no second authoritative state. The five methods
 * mirror the W03 wire DTOs one to one.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../../internal/app/contracts/models.js";

/**
 * AgentPrepare reserves one turn slot. Idempotent per request ID.
 * @param {contracts$0.PrepareTurnRequest} request
 * @returns {$CancellablePromise<contracts$0.PreparedTurn>}
 */
export function AgentPrepare(request) {
    return $Call.ByID(3172602556, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AgentReadEvents pages turn events after a decimal-string cursor.
 * @param {string} turnID
 * @param {string} afterSequence
 * @param {number} limit
 * @returns {$CancellablePromise<contracts$0.EventPage>}
 */
export function AgentReadEvents(turnID, afterSequence, limit) {
    return $Call.ByID(4134149572, turnID, afterSequence, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AgentSnapshot returns the authoritative turn projection.
 * @param {string} turnID
 * @returns {$CancellablePromise<contracts$0.TurnSnapshot>}
 */
export function AgentSnapshot(turnID) {
    return $Call.ByID(1938931437, turnID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * AgentStart starts a prepared turn. Idempotent retries never re-run the
 * driver.
 * @param {contracts$0.TurnCommand} command
 * @returns {$CancellablePromise<void>}
 */
export function AgentStart(command) {
    return $Call.ByID(1992686271, command);
}

/**
 * AgentStop converges one turn and returns its terminal snapshot.
 * @param {string} turnID
 * @param {string} reason
 * @returns {$CancellablePromise<contracts$0.TurnSnapshot>}
 */
export function AgentStop(turnID, reason) {
    return $Call.ByID(3522632773, turnID, reason).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = contracts$0.PreparedTurn.createFrom;
const $$createType1 = contracts$0.EventPage.createFrom;
const $$createType2 = contracts$0.TurnSnapshot.createFrom;
