// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.AppLockRuntimeState>}
 */
export function GetRuntimeState() {
    return $Call.ByID(1020892358).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ReportActivity() {
    return $Call.ByID(2874882766);
}

/**
 * @param {string} reason
 * @returns {$CancellablePromise<$models.AppLockRuntimeState>}
 */
export function SetRuntimeLocked(reason) {
    return $Call.ByID(357214711, reason).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AppLockRuntimeState.createFrom;
