// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function Disable(password) {
    return $Call.ByID(2017783423, password);
}

/**
 * @param {string} password
 * @returns {$CancellablePromise<$models.AppLockRuntimeState>}
 */
export function Enable(password) {
    return $Call.ByID(3197078282, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AppLockRuntimeState>}
 */
export function GetRuntimeState() {
    return $Call.ByID(1020892358).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetSettings() {
    return $Call.ByID(1126324894).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.BiometricStatus>}
 */
export function GetSystemUnlockStatus() {
    return $Call.ByID(431412744).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ReportActivity() {
    return $Call.ByID(2874882766);
}

/**
 * @param {string} reason
 * @returns {$CancellablePromise<$models.AppLockRuntimeState>}
 */
export function SetRuntimeLocked(reason) {
    return $Call.ByID(357214711, reason).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {boolean} enabled
 * @param {string} password
 * @param {boolean} autoPrompt
 * @returns {$CancellablePromise<$models.BiometricSettings>}
 */
export function SetSystemUnlockEnabled(enabled, password, autoPrompt) {
    return $Call.ByID(3477591759, enabled, password, autoPrompt).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function Unlock(password) {
    return $Call.ByID(3034665761, password);
}

/**
 * @returns {$CancellablePromise<$models.BiometricUnlockResult>}
 */
export function UnlockWithBiometrics() {
    return $Call.ByID(1610545362).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AppLockRuntimeState.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $models.BiometricStatus.createFrom;
const $$createType3 = $models.BiometricSettings.createFrom;
const $$createType4 = $models.BiometricUnlockResult.createFrom;
