// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as deeplink$0 from "../../internal/platform/deeplink/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<(deeplink$0.Action | null)[]>}
 */
export function Drain() {
    return $Call.ByID(3300770991).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<void>}
 */
export function Enqueue(rawURL) {
    return $Call.ByID(978817911, rawURL);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function EnqueueOpenTerminalPath(path) {
    return $Call.ByID(2370862464, path);
}

/**
 * @returns {$CancellablePromise<$models.DesktopToggleResult>}
 */
export function GetExplorerContextMenuEnabled() {
    return $Call.ByID(2352536659).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetJmsDeepLinkEnabled() {
    return $Call.ByID(2489131400);
}

/**
 * GetOSProtocolStatus reports whether the schemes currently hand off to this
 * executable. A drift (another tool took over ssh://) reads as unregistered.
 * @returns {$CancellablePromise<$models.ProtocolRegistrationResult>}
 */
export function GetOSProtocolStatus() {
    return $Call.ByID(614614681).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetSshDeepLinkEnabled() {
    return $Call.ByID(2975773976);
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<deeplink$0.Action | null>}
 */
export function Parse(rawURL) {
    return $Call.ByID(1147985370, rawURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function Pending() {
    return $Call.ByID(3235677350);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Ready() {
    return $Call.ByID(2105832758);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.DesktopToggleResult>}
 */
export function SetExplorerContextMenuEnabled(enabled) {
    return $Call.ByID(3260167135, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.DesktopToggleResult>}
 */
export function SetJmsDeepLinkEnabled(enabled) {
    return $Call.ByID(2680350412, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetOSProtocol registers or removes the ssh/telnet/netcatty URL schemes.
 * On Windows this writes HKCU\Software\Classes, which needs no elevation;
 * other platforms fail closed until their installer formats own registration.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.ProtocolRegistrationResult>}
 */
export function SetOSProtocol(enabled) {
    return $Call.ByID(896377307, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.DesktopToggleResult>}
 */
export function SetSshDeepLinkEnabled(enabled) {
    return $Call.ByID(3347299940, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = deeplink$0.Action.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.DesktopToggleResult.createFrom;
const $$createType4 = $models.ProtocolRegistrationResult.createFrom;
