// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {{ [_ in string]?: string }} agentEnv
 * @param {string} agentCommand
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function AccountInfo(agentEnv, agentCommand) {
    return $Call.ByID(2929325712, agentEnv, agentCommand).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} requestID
 * @param {string} chatSessionID
 * @returns {$CancellablePromise<$models.ExternalAgentResult>}
 */
export function Cancel(requestID, chatSessionID) {
    return $Call.ByID(1635323435, requestID, chatSessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} chatSessionID
 * @returns {$CancellablePromise<$models.ExternalAgentResult>}
 */
export function Cleanup(chatSessionID) {
    return $Call.ByID(2709566563, chatSessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} agentCommand
 * @param {{ [_ in string]?: string }} agentEnv
 * @returns {$CancellablePromise<$models.ExternalAgentResult>}
 */
export function CodexAppServerStatus(agentCommand, agentEnv) {
    return $Call.ByID(3671758118, agentCommand, agentEnv).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sdkBackend
 * @param {string} cwd
 * @param {string} providerID
 * @param {string} chatSessionID
 * @param {{ [_ in string]?: string }} agentEnv
 * @param {string} agentCommand
 * @param {string} codexRuntime
 * @returns {$CancellablePromise<$models.ExternalAgentModelsResult>}
 */
export function ListModels(sdkBackend, cwd, providerID, chatSessionID, agentEnv, agentCommand, codexRuntime) {
    return $Call.ByID(1965670383, sdkBackend, cwd, providerID, chatSessionID, agentEnv, agentCommand, codexRuntime).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} requestID
 * @param {string} chatSessionID
 * @param {string} prompt
 * @param {$models.ExternalAgentImage[]} images
 * @param {string} clientUserMessageID
 * @returns {$CancellablePromise<$models.ExternalAgentSteerResult>}
 */
export function Steer(requestID, chatSessionID, prompt, images, clientUserMessageID) {
    return $Call.ByID(3819942534, requestID, chatSessionID, prompt, images, clientUserMessageID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {$models.ExternalAgentStreamRequest} request
 * @returns {$CancellablePromise<$models.ExternalAgentResult>}
 */
export function Stream(request) {
    return $Call.ByID(1387901141, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.ExternalAgentResult.createFrom;
const $$createType2 = $models.ExternalAgentModelsResult.createFrom;
const $$createType3 = $models.ExternalAgentSteerResult.createFrom;
