// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filesystem$0 from "../../internal/platform/filesystem/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.TempClearResult>}
 */
export function ClearTemp() {
    return $Call.ByID(571030481).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} archivePath
 * @param {string} destinationRoot
 * @returns {$CancellablePromise<number>}
 */
export function ExtractArchive(archivePath, destinationRoot) {
    return $Call.ByID(3240863779, archivePath, destinationRoot);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function HomeDir() {
    return $Call.ByID(1121754232);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<filesystem$0.LocalEntry[]>}
 */
export function ListDir(path) {
    return $Call.ByID(729165017, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * StageAppend writes one base64-decoded chunk at offset. []byte bindings
 * arrive base64-encoded through the Wails transport.
 * @param {string} tempPath
 * @param {number} offset
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function StageAppend(tempPath, offset, data) {
    return $Call.ByID(398939544, tempPath, offset, data);
}

/**
 * StageBegin creates a temp file for a renderer-staged upload and returns
 * its path. The renderer streams chunks via StageAppend.
 * @param {string} fileName
 * @returns {$CancellablePromise<string>}
 */
export function StageBegin(fileName) {
    return $Call.ByID(3961908005, fileName);
}

/**
 * StageDiscard removes a staged temp file. Only LemonSSH staging files are
 * eligible so a renderer cannot delete arbitrary paths.
 * @param {string} tempPath
 * @returns {$CancellablePromise<void>}
 */
export function StageDiscard(tempPath) {
    return $Call.ByID(3485451546, tempPath);
}

/**
 * StageFromLocalPath copies one local file into the LemonSSH staging temp
 * directory in a single call (stat → open → copy with no renderer round trip
 * in between), so transient drag sources and path quirks cannot race the
 * upload. Returns the staged temp path and original size.
 * @param {string} path
 * @returns {$CancellablePromise<[string, number]>}
 */
export function StageFromLocalPath(path) {
    return $Call.ByID(1820087868, path);
}

/**
 * StatPath stats one local path (read-only) so dropped files can be
 * classified before upload.
 * @param {string} path
 * @returns {$CancellablePromise<$models.LocalPathStat>}
 */
export function StatPath(path) {
    return $Call.ByID(1999196219, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function TempFilePath(name) {
    return $Call.ByID(3262733025, name);
}

/**
 * @returns {$CancellablePromise<$models.TempDirectoryInfo>}
 */
export function TempInfo() {
    return $Call.ByID(3758389736).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.TempClearResult.createFrom;
const $$createType1 = filesystem$0.LocalEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.LocalPathStat.createFrom;
const $$createType4 = $models.TempDirectoryInfo.createFrom;
