// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} archivePath
 * @param {string} destinationRoot
 * @returns {$CancellablePromise<number>}
 */
export function ExtractArchive(archivePath, destinationRoot) {
    return $Call.ByID(3240863779, archivePath, destinationRoot);
}

/**
 * StageAppend writes one base64-decoded chunk at offset. []byte bindings
 * arrive base64-encoded through the Wails transport.
 * @param {string} tempPath
 * @param {number} offset
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function StageAppend(tempPath, offset, data) {
    return $Call.ByID(398939544, tempPath, offset, data);
}

/**
 * StageBegin creates a temp file for a renderer-staged upload and returns
 * its path. The renderer streams chunks via StageAppend.
 * @param {string} fileName
 * @returns {$CancellablePromise<string>}
 */
export function StageBegin(fileName) {
    return $Call.ByID(3961908005, fileName);
}

/**
 * StageDiscard removes a staged temp file. Only LemonSSH staging files are
 * eligible so a renderer cannot delete arbitrary paths.
 * @param {string} tempPath
 * @returns {$CancellablePromise<void>}
 */
export function StageDiscard(tempPath) {
    return $Call.ByID(3485451546, tempPath);
}

/**
 * StatPath stats one local path (read-only) so dropped files can be
 * classified before upload.
 * @param {string} path
 * @returns {$CancellablePromise<$models.LocalPathStat>}
 */
export function StatPath(path) {
    return $Call.ByID(1999196219, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.LocalPathStat.createFrom;
