// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} archivePath
 * @param {string} destinationRoot
 * @returns {$CancellablePromise<number>}
 */
export function ExtractArchive(archivePath, destinationRoot) {
    return $Call.ByID(3240863779, archivePath, destinationRoot);
}
