// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as forward$0 from "../../internal/terminal/forward/models.js";

/**
 * @returns {$CancellablePromise<forward$0.State[]>}
 */
export function List() {
    return $Call.ByID(2411316348).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<forward$0.State>}
 */
export function Snapshot(id) {
    return $Call.ByID(3731049984, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @param {string} kind
 * @param {string} bindHost
 * @param {number} bindPort
 * @param {string} targetHost
 * @param {number} targetPort
 * @param {string} sshHost
 * @param {number} sshPort
 * @param {string} username
 * @param {string} password
 * @returns {$CancellablePromise<forward$0.State>}
 */
export function Start(id, kind, bindHost, bindPort, targetHost, targetPort, sshHost, sshPort, username, password) {
    return $Call.ByID(1065595960, id, kind, bindHost, bindPort, targetHost, targetPort, sshHost, sshPort, username, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<forward$0.State>}
 */
export function Stop(id) {
    return $Call.ByID(3637837660, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = forward$0.State.createFrom;
const $$createType1 = $Create.Array($$createType0);
