// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ForwardService is the Wails-facing facade over internal/app/forwarduse. It
 * owns only shell wiring: renderer service registration and the shell epoch
 * label. All forward rules (tunnel lifecycle, SOCKS5 handling, port binding,
 * relaying) live in the shared forwarduse.Service, so a future capability
 * dispatch entry point can call the same instance.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as forwarduse$0 from "../../internal/app/forwarduse/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminaluse$0 from "../../internal/app/terminaluse/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List reports all active tunnels with their live status.
 * @returns {$CancellablePromise<$models.PortForwardListItem[]>}
 */
export function List() {
    return $Call.ByID(2411316348).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RuntimeSnapshot renders the tunnel table for the renderer poll, stamped
 * with this shell's epoch.
 * @returns {$CancellablePromise<$models.PortForwardRuntimeSnapshot>}
 */
export function RuntimeSnapshot() {
    return $Call.ByID(1667287404).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Snapshot reports one tunnel's status.
 * @param {string} id
 * @returns {$CancellablePromise<$models.PortForwardResult>}
 */
export function Snapshot(id) {
    return $Call.ByID(3731049984, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Start starts (or reuses) one tunnel for the rule encoded in id.
 * @param {string} id
 * @param {string} kind
 * @param {string} bindHost
 * @param {number} bindPort
 * @param {string} targetHost
 * @param {number} targetPort
 * @param {$models.SSHConnectRequest} request
 * @returns {$CancellablePromise<$models.PortForwardResult>}
 */
export function Start(id, kind, bindHost, bindPort, targetHost, targetPort, request) {
    return $Call.ByID(1065595960, id, kind, bindHost, bindPort, targetHost, targetPort, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Stop stops one tunnel and returns its lease to the pool.
 * @param {string} id
 * @returns {$CancellablePromise<$models.PortForwardResult>}
 */
export function Stop(id) {
    return $Call.ByID(3637837660, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * StopByRuleId stops every tunnel started for one rule.
 * @param {string} ruleID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function StopByRuleId(ruleID) {
    return $Call.ByID(4129056370, ruleID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = forwarduse$0.ListItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = forwarduse$0.RuntimeSnapshot.createFrom;
const $$createType3 = forwarduse$0.Result.createFrom;
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
