// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppLockRuntimeState {
    /**
     * Creates a new AppLockRuntimeState instance.
     * @param {Partial<AppLockRuntimeState>} [$$source = {}] - The source object to create the AppLockRuntimeState.
     */
    constructor($$source = {}) {
        if (!("initialized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["initialized"] = false;
        }
        if (!("locked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["locked"] = false;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["reason"] = null;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("lastLockedAt" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["lastLockedAt"] = null;
        }
        if (!("lastUnlockedAt" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["lastUnlockedAt"] = null;
        }
        if (!("lastActivityAt" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["lastActivityAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppLockRuntimeState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppLockRuntimeState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppLockRuntimeState(/** @type {Partial<AppLockRuntimeState>} */($$parsedSource));
    }
}

export class HotkeyResult {
    /**
     * Creates a new HotkeyResult instance.
     * @param {Partial<HotkeyResult>} [$$source = {}] - The source object to create the HotkeyResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["accelerator"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HotkeyResult(/** @type {Partial<HotkeyResult>} */($$parsedSource));
    }
}

export class HotkeyStatus {
    /**
     * Creates a new HotkeyStatus instance.
     * @param {Partial<HotkeyStatus>} [$$source = {}] - The source object to create the HotkeyStatus.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("hotkey" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["hotkey"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HotkeyStatus(/** @type {Partial<HotkeyStatus>} */($$parsedSource));
    }
}

/**
 * LocalPathStat is the os.Stat view of one local path.
 */
export class LocalPathStat {
    /**
     * Creates a new LocalPathStat instance.
     * @param {Partial<LocalPathStat>} [$$source = {}] - The source object to create the LocalPathStat.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalPathStat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalPathStat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalPathStat(/** @type {Partial<LocalPathStat>} */($$parsedSource));
    }
}

export class PopupOpenResult {
    /**
     * Creates a new PopupOpenResult instance.
     * @param {Partial<PopupOpenResult>} [$$source = {}] - The source object to create the PopupOpenResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["popupId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PopupOpenResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PopupOpenResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PopupOpenResult(/** @type {Partial<PopupOpenResult>} */($$parsedSource));
    }
}

/**
 * SSHConnectRequest is the Wails-facing SSH dial payload. JumpHosts nest;
 * command proxies and certificates remain fail-closed in the renderer mapper.
 */
export class SSHConnectRequest {
    /**
     * Creates a new SSHConnectRequest instance.
     * @param {Partial<SSHConnectRequest>} [$$source = {}] - The source object to create the SSHConnectRequest.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("privateKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["privateKey"] = "";
        }
        if (!("passphrase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["passphrase"] = "";
        }
        if (!("certificate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["certificate"] = "";
        }
        if (!("proxyUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyUrl"] = "";
        }
        if (!("enableMfa" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableMfa"] = false;
        }
        if (!("useAgent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useAgent"] = false;
        }
        if (!("identityFilePaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["identityFilePaths"] = [];
        }
        if (!("cols" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }
        if (!("jumpHosts" in $$source)) {
            /**
             * @member
             * @type {SSHConnectRequest[]}
             */
            this["jumpHosts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnectRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConnectRequest}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identityFilePaths" in $$parsedSource) {
            $$parsedSource["identityFilePaths"] = $$createField10_0($$parsedSource["identityFilePaths"]);
        }
        if ("jumpHosts" in $$parsedSource) {
            $$parsedSource["jumpHosts"] = $$createField13_0($$parsedSource["jumpHosts"]);
        }
        return new SSHConnectRequest(/** @type {Partial<SSHConnectRequest>} */($$parsedSource));
    }
}

/**
 * UpgradeStatus is the wire view of the persisted sequence.
 */
export class UpgradeStatus {
    /**
     * Creates a new UpgradeStatus instance.
     * @param {Partial<UpgradeStatus>} [$$source = {}] - The source object to create the UpgradeStatus.
     */
    constructor($$source = {}) {
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }
        if (!("step" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["step"] = "";
        }
        if (!("history" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpgradeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpgradeStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField3_0($$parsedSource["history"]);
        }
        return new UpgradeStatus(/** @type {Partial<UpgradeStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SSHConnectRequest.createFrom;
const $$createType2 = $Create.Array($$createType1);
