// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as transfer$0 from "../../internal/terminal/transfer/models.js";

export class AppLockRuntimeState {
    /**
     * Creates a new AppLockRuntimeState instance.
     * @param {Partial<AppLockRuntimeState>} [$$source = {}] - The source object to create the AppLockRuntimeState.
     */
    constructor($$source = {}) {
        if (!("initialized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["initialized"] = false;
        }
        if (!("locked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["locked"] = false;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["reason"] = null;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("lastLockedAt" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["lastLockedAt"] = null;
        }
        if (!("lastUnlockedAt" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["lastUnlockedAt"] = null;
        }
        if (!("lastActivityAt" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["lastActivityAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppLockRuntimeState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppLockRuntimeState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppLockRuntimeState(/** @type {Partial<AppLockRuntimeState>} */($$parsedSource));
    }
}

export class BiometricSettings {
    /**
     * Creates a new BiometricSettings instance.
     * @param {Partial<BiometricSettings>} [$$source = {}] - The source object to create the BiometricSettings.
     */
    constructor($$source = {}) {
        if (!("systemUnlockEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["systemUnlockEnabled"] = false;
        }
        if (!("systemUnlockAutoPromptEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["systemUnlockAutoPromptEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BiometricSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BiometricSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BiometricSettings(/** @type {Partial<BiometricSettings>} */($$parsedSource));
    }
}

export class BiometricStatus {
    /**
     * Creates a new BiometricStatus instance.
     * @param {Partial<BiometricStatus>} [$$source = {}] - The source object to create the BiometricStatus.
     */
    constructor($$source = {}) {
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["label"] = null;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["reason"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BiometricStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BiometricStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BiometricStatus(/** @type {Partial<BiometricStatus>} */($$parsedSource));
    }
}

export class BiometricUnlockResult {
    /**
     * Creates a new BiometricUnlockResult instance.
     * @param {Partial<BiometricUnlockResult>} [$$source = {}] - The source object to create the BiometricUnlockResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BiometricUnlockResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BiometricUnlockResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BiometricUnlockResult(/** @type {Partial<BiometricUnlockResult>} */($$parsedSource));
    }
}

export class CloudSyncDeleteResult {
    /**
     * Creates a new CloudSyncDeleteResult instance.
     * @param {Partial<CloudSyncDeleteResult>} [$$source = {}] - The source object to create the CloudSyncDeleteResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudSyncDeleteResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CloudSyncDeleteResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloudSyncDeleteResult(/** @type {Partial<CloudSyncDeleteResult>} */($$parsedSource));
    }
}

export class CloudSyncDownloadResult {
    /**
     * Creates a new CloudSyncDownloadResult instance.
     * @param {Partial<CloudSyncDownloadResult>} [$$source = {}] - The source object to create the CloudSyncDownloadResult.
     */
    constructor($$source = {}) {
        if (!("syncedFile" in $$source)) {
            /**
             * @member
             * @type {CloudSyncSyncedFile | null}
             */
            this["syncedFile"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudSyncDownloadResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CloudSyncDownloadResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("syncedFile" in $$parsedSource) {
            $$parsedSource["syncedFile"] = $$createField0_0($$parsedSource["syncedFile"]);
        }
        return new CloudSyncDownloadResult(/** @type {Partial<CloudSyncDownloadResult>} */($$parsedSource));
    }
}

export class CloudSyncResource {
    /**
     * Creates a new CloudSyncResource instance.
     * @param {Partial<CloudSyncResource>} [$$source = {}] - The source object to create the CloudSyncResource.
     */
    constructor($$source = {}) {
        if (!("resourceId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["resourceId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudSyncResource instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CloudSyncResource}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloudSyncResource(/** @type {Partial<CloudSyncResource>} */($$parsedSource));
    }
}

/**
 * CloudSyncSyncedFile mirrors the renderer's SyncedFile: meta is the
 * encryption envelope, payload is the base64 ciphertext. The pair is stored
 * verbatim on the remote so download returns it byte-identical.
 */
export class CloudSyncSyncedFile {
    /**
     * Creates a new CloudSyncSyncedFile instance.
     * @param {Partial<CloudSyncSyncedFile>} [$$source = {}] - The source object to create the CloudSyncSyncedFile.
     */
    constructor($$source = {}) {
        if (!("meta" in $$source)) {
            /**
             * @member
             * @type {json$0.RawMessage}
             */
            this["meta"] = null;
        }
        if (!("payload" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["payload"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["etag"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudSyncSyncedFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CloudSyncSyncedFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloudSyncSyncedFile(/** @type {Partial<CloudSyncSyncedFile>} */($$parsedSource));
    }
}

/**
 * CloudSyncWebDAVConfig mirrors the renderer's WebDAVConfig. Token-based auth
 * is fail-closed: the Go WebDAV transport implements basic auth only.
 */
export class CloudSyncWebDAVConfig {
    /**
     * Creates a new CloudSyncWebDAVConfig instance.
     * @param {Partial<CloudSyncWebDAVConfig>} [$$source = {}] - The source object to create the CloudSyncWebDAVConfig.
     */
    constructor($$source = {}) {
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["authType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["username"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["token"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["allowInsecure"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudSyncWebDAVConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CloudSyncWebDAVConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloudSyncWebDAVConfig(/** @type {Partial<CloudSyncWebDAVConfig>} */($$parsedSource));
    }
}

export class HotkeyResult {
    /**
     * Creates a new HotkeyResult instance.
     * @param {Partial<HotkeyResult>} [$$source = {}] - The source object to create the HotkeyResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["accelerator"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HotkeyResult(/** @type {Partial<HotkeyResult>} */($$parsedSource));
    }
}

export class HotkeyStatus {
    /**
     * Creates a new HotkeyStatus instance.
     * @param {Partial<HotkeyStatus>} [$$source = {}] - The source object to create the HotkeyStatus.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("hotkey" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["hotkey"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HotkeyStatus(/** @type {Partial<HotkeyStatus>} */($$parsedSource));
    }
}

/**
 * LocalPathStat is the os.Stat view of one local path.
 */
export class LocalPathStat {
    /**
     * Creates a new LocalPathStat instance.
     * @param {Partial<LocalPathStat>} [$$source = {}] - The source object to create the LocalPathStat.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalPathStat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalPathStat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalPathStat(/** @type {Partial<LocalPathStat>} */($$parsedSource));
    }
}

/**
 * MoshStartRequest is the Wails-facing Mosh/ET bootstrap payload. The union of
 * SSH dial fields lets the handshake reuse the same auth path as Connect.
 */
export class MoshStartRequest {
    /**
     * Creates a new MoshStartRequest instance.
     * @param {Partial<MoshStartRequest>} [$$source = {}] - The source object to create the MoshStartRequest.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("privateKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["privateKey"] = "";
        }
        if (!("passphrase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["passphrase"] = "";
        }
        if (!("certificate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["certificate"] = "";
        }
        if (!("proxyUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyUrl"] = "";
        }
        if (!("proxyCommand" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyCommand"] = "";
        }
        if (!("enableMfa" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableMfa"] = false;
        }
        if (!("useAgent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useAgent"] = false;
        }
        if (!("identityFilePaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["identityFilePaths"] = [];
        }
        if (!("jumpHosts" in $$source)) {
            /**
             * @member
             * @type {SSHConnectRequest[]}
             */
            this["jumpHosts"] = [];
        }
        if (!("clientPath" in $$source)) {
            /**
             * ClientPath is the absolute path to the local mosh-client / et binary.
             * @member
             * @type {string}
             */
            this["clientPath"] = "";
        }
        if (!("serverPath" in $$source)) {
            /**
             * ServerPath overrides the remote mosh-server command (empty uses default).
             * @member
             * @type {string}
             */
            this["serverPath"] = "";
        }
        if (!("cols" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoshStartRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MoshStartRequest}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType2;
        const $$createField12_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identityFilePaths" in $$parsedSource) {
            $$parsedSource["identityFilePaths"] = $$createField11_0($$parsedSource["identityFilePaths"]);
        }
        if ("jumpHosts" in $$parsedSource) {
            $$parsedSource["jumpHosts"] = $$createField12_0($$parsedSource["jumpHosts"]);
        }
        return new MoshStartRequest(/** @type {Partial<MoshStartRequest>} */($$parsedSource));
    }
}

/**
 * NativeStartRequest is the Wails-facing native plugin spawn payload.
 */
export class NativeStartRequest {
    /**
     * Creates a new NativeStartRequest instance.
     * @param {Partial<NativeStartRequest>} [$$source = {}] - The source object to create the NativeStartRequest.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("binaryPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["binaryPath"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("args" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["args"] = [];
        }
        if (!("workDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workDir"] = "";
        }
        if (!("env" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["env"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NativeStartRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NativeStartRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField3_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField5_0($$parsedSource["env"]);
        }
        return new NativeStartRequest(/** @type {Partial<NativeStartRequest>} */($$parsedSource));
    }
}

export class PopupOpenResult {
    /**
     * Creates a new PopupOpenResult instance.
     * @param {Partial<PopupOpenResult>} [$$source = {}] - The source object to create the PopupOpenResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["popupId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PopupOpenResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PopupOpenResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PopupOpenResult(/** @type {Partial<PopupOpenResult>} */($$parsedSource));
    }
}

/**
 * ProtocolRegistrationResult reports the OS handoff state for the URL schemes
 * LemonSSH owns (ssh, telnet, netcatty).
 */
export class ProtocolRegistrationResult {
    /**
     * Creates a new ProtocolRegistrationResult instance.
     * @param {Partial<ProtocolRegistrationResult>} [$$source = {}] - The source object to create the ProtocolRegistrationResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("registered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["registered"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtocolRegistrationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProtocolRegistrationResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtocolRegistrationResult(/** @type {Partial<ProtocolRegistrationResult>} */($$parsedSource));
    }
}

export class SFTPOpenRequest {
    /**
     * Creates a new SFTPOpenRequest instance.
     * @param {Partial<SFTPOpenRequest>} [$$source = {}] - The source object to create the SFTPOpenRequest.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("privateKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["privateKey"] = "";
        }
        if (!("passphrase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["passphrase"] = "";
        }
        if (!("certificate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["certificate"] = "";
        }
        if (!("proxyUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyUrl"] = "";
        }
        if (!("proxyCommand" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyCommand"] = "";
        }
        if (!("enableMfa" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableMfa"] = false;
        }
        if (!("useAgent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useAgent"] = false;
        }
        if (!("identityFilePaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["identityFilePaths"] = [];
        }
        if (!("cols" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }
        if (!("jumpHosts" in $$source)) {
            /**
             * @member
             * @type {SSHConnectRequest[]}
             */
            this["jumpHosts"] = [];
        }
        if (!("sudo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sudo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPOpenRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SFTPOpenRequest}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType2;
        const $$createField14_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identityFilePaths" in $$parsedSource) {
            $$parsedSource["identityFilePaths"] = $$createField11_0($$parsedSource["identityFilePaths"]);
        }
        if ("jumpHosts" in $$parsedSource) {
            $$parsedSource["jumpHosts"] = $$createField14_0($$parsedSource["jumpHosts"]);
        }
        return new SFTPOpenRequest(/** @type {Partial<SFTPOpenRequest>} */($$parsedSource));
    }
}

/**
 * SSHConnectRequest is the Wails-facing SSH dial payload. JumpHosts nest;
 * proxyCommand carries OpenSSH ProxyCommand semantics (%h/%p tokens).
 */
export class SSHConnectRequest {
    /**
     * Creates a new SSHConnectRequest instance.
     * @param {Partial<SSHConnectRequest>} [$$source = {}] - The source object to create the SSHConnectRequest.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("privateKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["privateKey"] = "";
        }
        if (!("passphrase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["passphrase"] = "";
        }
        if (!("certificate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["certificate"] = "";
        }
        if (!("proxyUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyUrl"] = "";
        }
        if (!("proxyCommand" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyCommand"] = "";
        }
        if (!("enableMfa" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableMfa"] = false;
        }
        if (!("useAgent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useAgent"] = false;
        }
        if (!("identityFilePaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["identityFilePaths"] = [];
        }
        if (!("cols" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }
        if (!("jumpHosts" in $$source)) {
            /**
             * @member
             * @type {SSHConnectRequest[]}
             */
            this["jumpHosts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnectRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConnectRequest}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType2;
        const $$createField14_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identityFilePaths" in $$parsedSource) {
            $$parsedSource["identityFilePaths"] = $$createField11_0($$parsedSource["identityFilePaths"]);
        }
        if ("jumpHosts" in $$parsedSource) {
            $$parsedSource["jumpHosts"] = $$createField14_0($$parsedSource["jumpHosts"]);
        }
        return new SSHConnectRequest(/** @type {Partial<SSHConnectRequest>} */($$parsedSource));
    }
}

/**
 * SerialStartRequest is the Wails-facing serial open payload. The renderer
 * forwards the full line configuration; the serial owner validates it and fails
 * closed on combinations the backend cannot honour.
 */
export class SerialStartRequest {
    /**
     * Creates a new SerialStartRequest instance.
     * @param {Partial<SerialStartRequest>} [$$source = {}] - The source object to create the SerialStartRequest.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("baudRate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["baudRate"] = 0;
        }
        if (!("dataBits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dataBits"] = 0;
        }
        if (!("stopBits" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stopBits"] = "";
        }
        if (!("parity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parity"] = "";
        }
        if (!("flowControl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["flowControl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerialStartRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SerialStartRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SerialStartRequest(/** @type {Partial<SerialStartRequest>} */($$parsedSource));
    }
}

/**
 * TelnetStartRequest is the Wails-facing telnet dial payload. Auto-login
 * credentials are held in memory for the prompt exchange and never persisted.
 */
export class TelnetStartRequest {
    /**
     * Creates a new TelnetStartRequest instance.
     * @param {Partial<TelnetStartRequest>} [$$source = {}] - The source object to create the TelnetStartRequest.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("cols" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("autoLogin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoLogin"] = false;
        }
        if (!("promptTimeoutSecs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["promptTimeoutSecs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TelnetStartRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TelnetStartRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TelnetStartRequest(/** @type {Partial<TelnetStartRequest>} */($$parsedSource));
    }
}

export class TempClearResult {
    /**
     * Creates a new TempClearResult instance.
     * @param {Partial<TempClearResult>} [$$source = {}] - The source object to create the TempClearResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("deletedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deletedCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TempClearResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TempClearResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TempClearResult(/** @type {Partial<TempClearResult>} */($$parsedSource));
    }
}

export class TempDirectoryInfo {
    /**
     * Creates a new TempDirectoryInfo instance.
     * @param {Partial<TempDirectoryInfo>} [$$source = {}] - The source object to create the TempDirectoryInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("fileCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileCount"] = 0;
        }
        if (!("totalSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TempDirectoryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TempDirectoryInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TempDirectoryInfo(/** @type {Partial<TempDirectoryInfo>} */($$parsedSource));
    }
}

export class TransferSnapshot {
    /**
     * Creates a new TransferSnapshot instance.
     * @param {Partial<TransferSnapshot>} [$$source = {}] - The source object to create the TransferSnapshot.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["phase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["controlKind"] = undefined;
        }
        if (!("lifecycleEpoch" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lifecycleEpoch"] = 0;
        }
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {transfer$0.State}
             */
            this["state"] = transfer$0.State.$zero;
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }
        if (!("doneBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["doneBytes"] = 0;
        }
        if (!("chunksDone" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunksDone"] = 0;
        }
        if (!("chunksTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunksTotal"] = 0;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("sourceSessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceSessionId"] = "";
        }
        if (!("targetSessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetSessionId"] = "";
        }
        if (!("sourcePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourcePath"] = "";
        }
        if (!("targetPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetPath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sourceHostId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetHostId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentTaskId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["directoryEntryIndex"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["directoryEntryIdentity"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TransferSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferSnapshot(/** @type {Partial<TransferSnapshot>} */($$parsedSource));
    }
}

export class TransferStartRequest {
    /**
     * Creates a new TransferStartRequest instance.
     * @param {Partial<TransferStartRequest>} [$$source = {}] - The source object to create the TransferStartRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sourceHostId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetHostId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentTaskId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["directoryEntryIndex"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["directoryEntryIdentity"] = undefined;
        }
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("sourceSessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceSessionId"] = "";
        }
        if (!("targetSessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetSessionId"] = "";
        }
        if (!("sourcePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourcePath"] = "";
        }
        if (!("targetPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferStartRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TransferStartRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferStartRequest(/** @type {Partial<TransferStartRequest>} */($$parsedSource));
    }
}

/**
 * UpgradeStatus is the wire view of the persisted sequence.
 */
export class UpgradeStatus {
    /**
     * Creates a new UpgradeStatus instance.
     * @param {Partial<UpgradeStatus>} [$$source = {}] - The source object to create the UpgradeStatus.
     */
    constructor($$source = {}) {
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }
        if (!("step" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["step"] = "";
        }
        if (!("history" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpgradeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpgradeStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField3_0($$parsedSource["history"]);
        }
        return new UpgradeStatus(/** @type {Partial<UpgradeStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = CloudSyncSyncedFile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = SSHConnectRequest.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
