// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UpgradeStatus is the wire view of the persisted sequence.
 */
export class UpgradeStatus {
    /**
     * Creates a new UpgradeStatus instance.
     * @param {Partial<UpgradeStatus>} [$$source = {}] - The source object to create the UpgradeStatus.
     */
    constructor($$source = {}) {
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }
        if (!("step" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["step"] = "";
        }
        if (!("history" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpgradeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpgradeStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField3_0($$parsedSource["history"]);
        }
        return new UpgradeStatus(/** @type {Partial<UpgradeStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
