// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NetcattyService is the Wails-facing facade. It holds no business logic:
 * every call delegates to internal/app use cases.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";

/**
 * Health reports application liveness to the renderer.
 * @returns {$CancellablePromise<app$0.HealthStatus>}
 */
export function Health() {
    return $Call.ByID(2498077617).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ResolveWindowRole validates a window role requested by a renderer.
 * @param {string} role
 * @returns {$CancellablePromise<app$0.WindowRoleInfo>}
 */
export function ResolveWindowRole(role) {
    return $Call.ByID(2381199965, role).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Version reports build identity to the renderer.
 * @returns {$CancellablePromise<app$0.VersionInfo>}
 */
export function Version() {
    return $Call.ByID(2850139721).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = app$0.HealthStatus.createFrom;
const $$createType1 = app$0.WindowRoleInfo.createFrom;
const $$createType2 = app$0.VersionInfo.createFrom;
