// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProfileService is the Wails-facing facade over the transactional profile
 * store (P2-02). It holds no policy: validation lives in the store.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../internal/profile/store/models.js";

/**
 * DeleteRaw removes one raw value.
 * @param {string} domain
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRaw(domain, key) {
    return $Call.ByID(1497012975, domain, key);
}

/**
 * Domains lists the declared profile domains.
 * @returns {$CancellablePromise<string[] | null>}
 */
export function Domains() {
    return $Call.ByID(3215331561);
}

/**
 * GetRaw returns one opaque raw value (base64 on the wire).
 * @param {string} domain
 * @param {string} key
 * @returns {$CancellablePromise<string | null>}
 */
export function GetRaw(domain, key) {
    return $Call.ByID(3656545750, domain, key);
}

/**
 * Revision reports the current committed profile revision.
 * @returns {$CancellablePromise<number>}
 */
export function Revision() {
    return $Call.ByID(2917505497);
}

/**
 * SetRaw writes one opaque raw value atomically.
 * @param {string} domain
 * @param {string} key
 * @param {string | null} value
 * @returns {$CancellablePromise<void>}
 */
export function SetRaw(domain, key, value) {
    return $Call.ByID(2387054098, domain, key, value);
}

/**
 * Write applies an atomic multi-key transaction with optional CAS.
 * @param {number} expectedRevision
 * @param {store$0.Mutation[] | null} mutations
 * @returns {$CancellablePromise<store$0.WriteResult>}
 */
export function Write(expectedRevision, mutations) {
    return $Call.ByID(2341111907, expectedRevision, mutations);
}
