// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProfileMigrationService is the Wails-facing import/verify/promote facade
 * (P2-06). It never promotes before migration.Import returns fully verified
 * mutations and StageProfile marks the complete staging store.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../internal/profile/store/models.js";

/**
 * ImportAndPromote verifies the encrypted bundle, re-seals secrets using the
 * platform provider, stages all mutations, and atomically promotes the result.
 * @param {string} bundleBase64
 * @param {string} targetPrivateKeyBase64
 * @param {string} fingerprint
 * @returns {$CancellablePromise<store$0.MigrationReceipt | null>}
 */
export function ImportAndPromote(bundleBase64, targetPrivateKeyBase64, fingerprint) {
    return $Call.ByID(2271569908, bundleBase64, targetPrivateKeyBase64, fingerprint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * VerifyBundle checks the encrypted bundle without writing or promoting.
 * @param {string} bundleBase64
 * @param {string} targetPrivateKeyBase64
 * @param {string} fingerprint
 * @returns {$CancellablePromise<number>}
 */
export function VerifyBundle(bundleBase64, targetPrivateKeyBase64, fingerprint) {
    return $Call.ByID(3562882483, bundleBase64, targetPrivateKeyBase64, fingerprint);
}

// Private type creation functions
const $$createType0 = store$0.MigrationReceipt.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
