// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProviderFetchService is the Go owner for renderer provider traffic: the
 * settings model-list/probe fetch (aiFetch), the temporary discovery
 * allowlist (aiAllowlistAddHost) and the provider-config allowlist rebuild
 * (aiSyncProviders). Every request runs through the netpolicy authority, so
 * URL, dial, redirect and body limits match providerHandlers.cjs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AllowlistAddHost registers one provider baseURL so discovery can reach it,
 * exactly like netcatty:ai:allowlist:add-host. The registration lives for the
 * process; the netpolicy guard (private ranges, metadata hosts, scheme rules)
 * still decides every request.
 * @param {string} baseURL
 * @returns {$CancellablePromise<$models.ProviderAllowlistResult>}
 */
export function AllowlistAddHost(baseURL) {
    return $Call.ByID(158542348, baseURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Fetch performs one policy-enforced provider request.
 * @param {$models.ProviderFetchRequest} request
 * @returns {$CancellablePromise<$models.ProviderFetchResult>}
 */
export function Fetch(request) {
    return $Call.ByID(158900326, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SyncProviders rebuilds the allowlist from the renderer's provider configs,
 * matching netcatty:ai:sync-providers (keys never cross this boundary).
 * @param {$models.ProviderEndpointConfig[]} providers
 * @returns {$CancellablePromise<$models.ProviderAllowlistResult>}
 */
export function SyncProviders(providers) {
    return $Call.ByID(3698317193, providers).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ProviderAllowlistResult.createFrom;
const $$createType1 = $models.ProviderFetchResult.createFrom;
