// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProviderFetchService is the Go owner for renderer provider traffic: the
 * settings model-list/probe fetch (aiFetch), the temporary discovery
 * allowlist (aiAllowlistAddHost) and the provider-config allowlist rebuild
 * (aiSyncProviders). Every request runs through the netpolicy authority, so
 * URL, dial, redirect and body limits match providerHandlers.cjs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AllowlistAddHost registers one provider baseURL so discovery can reach it,
 * exactly like netcatty:ai:allowlist:add-host. The registration lives for the
 * process; the netpolicy guard (private ranges, metadata hosts, scheme rules)
 * still decides every request.
 * @param {string} baseURL
 * @returns {$CancellablePromise<$models.ProviderAllowlistResult>}
 */
export function AllowlistAddHost(baseURL) {
    return $Call.ByID(158542348, baseURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function ChatCancel(id) {
    return $Call.ByID(1491973310, id);
}

/**
 * ChatStream returns when response headers arrive; the response body continues
 * on its own cancellable context because a Wails call ends after this return.
 * @param {string} id
 * @param {$models.ProviderFetchRequest} request
 * @param {number} idleTimeoutMs
 * @returns {$CancellablePromise<$models.ProviderStreamResult>}
 */
export function ChatStream(id, request, idleTimeoutMs) {
    return $Call.ByID(368282980, id, request, idleTimeoutMs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Fetch performs one policy-enforced provider request.
 * @param {$models.ProviderFetchRequest} request
 * @returns {$CancellablePromise<$models.ProviderFetchResult>}
 */
export function Fetch(request) {
    return $Call.ByID(158900326, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SyncProviders retains configured encrypted keys in host memory and registers
 * their endpoints. Plaintext keys are resolved only when sending a request.
 * @param {$models.ProviderEndpointConfig[]} providers
 * @returns {$CancellablePromise<$models.ProviderAllowlistResult>}
 */
export function SyncProviders(providers) {
    return $Call.ByID(3698317193, providers).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SyncWebSearch retains the encrypted search key in the native host and
 * registers the selected endpoint with the network policy. Passing an empty
 * host clears the credential when web search is disabled.
 * @param {string} apiHost
 * @param {string} apiKey
 * @returns {$CancellablePromise<$models.ProviderAllowlistResult>}
 */
export function SyncWebSearch(apiHost, apiKey) {
    return $Call.ByID(4027803969, apiHost, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ProviderAllowlistResult.createFrom;
const $$createType1 = $models.ProviderStreamResult.createFrom;
const $$createType2 = $models.ProviderFetchResult.createFrom;
