// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} directory
 * @returns {$CancellablePromise<$models.SessionLogsClearResult>}
 */
export function ClearDirectory(directory) {
    return $Call.ByID(3962862311, directory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} directory
 * @returns {$CancellablePromise<$models.ManualSessionLogResult>}
 */
export function OpenDirectory(directory) {
    return $Call.ByID(2756539510, directory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {string} filePath
 * @param {string} initialLine
 * @returns {$CancellablePromise<$models.ManualSessionLogResult>}
 */
export function Start(sessionID, filePath, initialLine) {
    return $Call.ByID(1919225857, sessionID, filePath, initialLine).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ManualSessionLogResult>}
 */
export function Status(sessionID) {
    return $Call.ByID(3053064837, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ManualSessionLogResult>}
 */
export function Stop(sessionID) {
    return $Call.ByID(385153403, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SessionLogsClearResult.createFrom;
const $$createType1 = $models.ManualSessionLogResult.createFrom;
