// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Close hides the window; the loaded page is kept for the next open.
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(3291979824);
}

/**
 * Open shows the settings window. If its first paint has not happened yet
 * (WebView2 renders nothing while hidden), the show is deferred until
 * PaintReady so the user never sees an empty black/white frame.
 * @returns {$CancellablePromise<boolean>}
 */
export function Open() {
    return $Call.ByID(1829813804);
}

/**
 * PaintReady is called by the settings page after its first render.
 * @returns {$CancellablePromise<boolean>}
 */
export function PaintReady() {
    return $Call.ByID(2750603191);
}

/**
 * Preload creates the hidden settings window off the boot path.
 * @returns {$CancellablePromise<void>}
 */
export function Preload() {
    return $Call.ByID(612480889);
}

/**
 * Show force-shows the window (explicit request path).
 * @returns {$CancellablePromise<void>}
 */
export function Show() {
    return $Call.ByID(3854190277);
}
