// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SFTPService exposes SFTP browsing and file transfer over the shared SSH
 * transport pool. Each Open call borrows a pooled transport (KindSFTP), opens
 * one SFTP subsystem client and registers it under an opaque session ID;
 * operations are bounded by the per-session client limit.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sftp$0 from "../../internal/terminal/sftp/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close releases the SFTP client and returns the transport to the pool.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function Close(sessionID) {
    return $Call.ByID(3365137644, sessionID);
}

/**
 * Download streams a remote file to a local destination path.
 * @param {string} sessionID
 * @param {string} remotePath
 * @param {string} localPath
 * @returns {$CancellablePromise<number>}
 */
export function Download(sessionID, remotePath, localPath) {
    return $Call.ByID(794644904, sessionID, remotePath, localPath);
}

/**
 * ExtractArchive downloads a remote zip, extracts it locally with zip-slip
 * protection, and uploads the files next to the archive.
 * @param {string} sessionID
 * @param {string} remotePath
 * @returns {$CancellablePromise<number>}
 */
export function ExtractArchive(sessionID, remotePath) {
    return $Call.ByID(3471517857, sessionID, remotePath);
}

/**
 * HomeDir returns the remote working directory for the SFTP session.
 * @param {string} sessionID
 * @returns {$CancellablePromise<string>}
 */
export function HomeDir(sessionID) {
    return $Call.ByID(1651492542, sessionID);
}

/**
 * List returns one directory listing (directories first, name-ordered).
 * @param {string} sessionID
 * @param {string} dir
 * @returns {$CancellablePromise<sftp$0.Entry[]>}
 */
export function List(sessionID, dir) {
    return $Call.ByID(269609792, sessionID, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Mkdir creates a remote directory.
 * @param {string} sessionID
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function Mkdir(sessionID, dir) {
    return $Call.ByID(1975574083, sessionID, dir);
}

/**
 * Open dials (or borrows) a transport for host and registers an SFTP session.
 * @param {$models.SSHConnectRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function Open(request) {
    return $Call.ByID(3618100000, request);
}

/**
 * Read returns a remote file as UTF-8 text.
 * @param {string} sessionID
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function Read(sessionID, remotePath) {
    return $Call.ByID(3756744012, sessionID, remotePath);
}

/**
 * Remove deletes a remote file or directory tree.
 * @param {string} sessionID
 * @param {string} target
 * @returns {$CancellablePromise<void>}
 */
export function Remove(sessionID, target) {
    return $Call.ByID(1547806816, sessionID, target);
}

/**
 * Rename moves or renames a remote path.
 * @param {string} sessionID
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function Rename(sessionID, oldPath, newPath) {
    return $Call.ByID(514287290, sessionID, oldPath, newPath);
}

/**
 * Stat stats one remote path.
 * @param {string} sessionID
 * @param {string} target
 * @returns {$CancellablePromise<sftp$0.FileInfo>}
 */
export function Stat(sessionID, target) {
    return $Call.ByID(2968321290, sessionID, target).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Upload streams a local file to a remote destination path.
 * @param {string} sessionID
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<number>}
 */
export function Upload(sessionID, localPath, remotePath) {
    return $Call.ByID(3196629929, sessionID, localPath, remotePath);
}

/**
 * UploadCompressedFolder zips a local folder and uploads the archive.
 * @param {string} sessionID
 * @param {string} localFolder
 * @param {string} remoteZipPath
 * @returns {$CancellablePromise<number>}
 */
export function UploadCompressedFolder(sessionID, localFolder, remoteZipPath) {
    return $Call.ByID(3644613492, sessionID, localFolder, remoteZipPath);
}

/**
 * WriteText writes UTF-8 text to a remote file, creating or truncating it.
 * @param {string} sessionID
 * @param {string} remotePath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteText(sessionID, remotePath, content) {
    return $Call.ByID(2088554336, sessionID, remotePath, content);
}

// Private type creation functions
const $$createType0 = sftp$0.Entry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = sftp$0.FileInfo.createFrom;
