// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function List() {
    return $Call.ByID(1745414907).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} raw
 * @param {string} callbackID
 * @returns {$CancellablePromise<void>}
 */
export function Register(raw, callbackID) {
    return $Call.ByID(1316855942, raw, callbackID);
}

/**
 * @param {string} raw
 * @returns {$CancellablePromise<void>}
 */
export function Unregister(raw) {
    return $Call.ByID(2049886653, raw);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
