// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as syncengine$0 from "../../internal/syncengine/models.js";

/**
 * @param {{ [_ in string]?: syncengine$0.Entry }} entries
 * @returns {$CancellablePromise<string>}
 */
export function Fingerprint(entries) {
    return $Call.ByID(542796586, entries);
}

/**
 * @param {{ [_ in string]?: syncengine$0.Entry }} local
 * @param {{ [_ in string]?: syncengine$0.Entry }} remote
 * @returns {$CancellablePromise<{ [_ in string]?: syncengine$0.Entry }>}
 */
export function Merge(local, remote) {
    return $Call.ByID(3140789034, local, remote).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = syncengine$0.Entry.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
