// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService owns SSH terminal sessions end-to-end: SSH dial → auth →
 * PTY channel → data plane streaming → renderer WebSocket. Each session gets
 * a route bootstrap (generation + one-use tokens) that the renderer exchanges
 * for the loopback data/urgent WebSocket connections.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dataplane$0 from "../../internal/terminal/dataplane/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serialport$0 from "../../internal/terminal/serialport/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ymodem$0 from "../../internal/terminal/ymodem/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bootstrap returns the route credentials the renderer needs to attach its
 * data/urgent WebSockets for a session.
 * @param {string} sessionID
 * @returns {$CancellablePromise<dataplane$0.RouteBootstrap>}
 */
export function Bootstrap(sessionID) {
    return $Call.ByID(2388013009, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CancelZmodem honours the existing CRC/safety cancellation boundary. A
 * cancellation is only meaningful for a live receiver, so it is reported as a
 * no-op success when nothing is in flight rather than as a spurious failure.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CancelZmodem(sessionID) {
    return $Call.ByID(2146045067, sessionID);
}

/**
 * Close tears the PTY, transport and data plane route down.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function Close(sessionID) {
    return $Call.ByID(3052890075, sessionID);
}

/**
 * Connect dials SSH, authenticates, opens a PTY shell and starts streaming
 * output into the data plane. It returns the session ID; call Bootstrap to
 * get the route credentials for the renderer WebSocket.
 * @param {$models.SSHConnectRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function Connect(request) {
    return $Call.ByID(4197416449, request);
}

/**
 * GetTelnetEchoMode reports whether the server currently echoes input.
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetTelnetEchoMode(sessionID) {
    return $Call.ByID(2459092297, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListSerialPorts enumerates OS serial devices.
 * @returns {$CancellablePromise<serialport$0.Info[]>}
 */
export function ListSerialPorts() {
    return $Call.ByID(663993127).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListenAddr exposes the bound loopback data plane address (host:port).
 * @returns {$CancellablePromise<string>}
 */
export function ListenAddr() {
    return $Call.ByID(305533821);
}

/**
 * ReceiveSerialYmodem downloads files from the serial peer into destinationDir.
 * @param {string} sessionID
 * @param {string} destinationDir
 * @returns {$CancellablePromise<ymodem$0.ReceiveResult[]>}
 */
export function ReceiveSerialYmodem(sessionID, destinationDir) {
    return $Call.ByID(3045917549, sessionID, destinationDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Resize updates the remote PTY window size.
 * @param {string} sessionID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(sessionID, cols, rows) {
    return $Call.ByID(270758441, sessionID, cols, rows);
}

/**
 * RespondKeyboardInteractive completes or cancels a pending MFA challenge.
 * @param {string} requestID
 * @param {string[]} responses
 * @param {boolean} cancelled
 * @returns {$CancellablePromise<void>}
 */
export function RespondKeyboardInteractive(requestID, responses, cancelled) {
    return $Call.ByID(547631165, requestID, responses, cancelled);
}

/**
 * SendSerialYmodem uploads the file at filePath over the session's serial port
 * using the YMODEM block protocol.
 * @param {string} sessionID
 * @param {string} filePath
 * @returns {$CancellablePromise<ymodem$0.SendResult>}
 */
export function SendSerialYmodem(sessionID, filePath) {
    return $Call.ByID(4074171664, sessionID, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {any} emit
 * @returns {$CancellablePromise<void>}
 */
export function SetChallengeEmitter(emit) {
    return $Call.ByID(3085412466, emit);
}

/**
 * SetEventEmitter wires renderer-visible events (telnet echo mode, auto-login
 * completion/cancellation) to the Wails event bus.
 * @param {any} emit
 * @returns {$CancellablePromise<void>}
 */
export function SetEventEmitter(emit) {
    return $Call.ByID(829485873, emit);
}

/**
 * Signal delivers a POSIX signal name (e.g. "KILL") to the remote shell.
 * @param {string} sessionID
 * @param {string} signal
 * @returns {$CancellablePromise<void>}
 */
export function Signal(sessionID, signal) {
    return $Call.ByID(4236247009, sessionID, signal);
}

/**
 * StartEt runs the Eternal Terminal bootstrap. ET uses the same supervised
 * process model; the remote command differs but the local supervision and
 * data-plane wiring are identical to Mosh.
 * @param {$models.MoshStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartEt(request) {
    return $Call.ByID(2928365382, request);
}

/**
 * StartLocal launches a local PTY and streams it on the same data plane as SSH.
 * @param {string} shell
 * @param {string} cwd
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<string>}
 */
export function StartLocal(shell, cwd, cols, rows) {
    return $Call.ByID(3430581078, shell, cwd, cols, rows);
}

/**
 * StartMosh runs the mosh bootstrap over SSH and supervises the local
 * mosh-client. The remote handshake scrapes the MOSH CONNECT line, then the
 * client process streams through the same data plane as other sessions.
 * @param {$models.MoshStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartMosh(request) {
    return $Call.ByID(2465988376, request);
}

/**
 * StartSerial opens a serial port and streams bytes onto the data plane.
 * @param {$models.SerialStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartSerial(request) {
    return $Call.ByID(2462094395, request);
}

/**
 * StartTelnet dials a Telnet host and streams IAC-decoded data onto the same
 * data plane as SSH/local PTY. Echo mode transitions are surfaced as events so
 * the renderer can disable local echo when the server takes over; when
 * auto-login is requested the prompt exchange runs against the live stream.
 * @param {$models.TelnetStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartTelnet(request) {
    return $Call.ByID(3093898707, request);
}

/**
 * Write sends raw stdin bytes to the remote shell.
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<number>}
 */
export function Write(sessionID, data) {
    return $Call.ByID(371925220, sessionID, data);
}

// Private type creation functions
const $$createType0 = dataplane$0.RouteBootstrap.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = serialport$0.Info.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ymodem$0.ReceiveResult.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ymodem$0.SendResult.createFrom;
