// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService owns SSH terminal sessions end-to-end: SSH dial → auth →
 * PTY channel → data plane streaming → renderer WebSocket. Each session gets
 * a route bootstrap (generation + one-use tokens) that the renderer exchanges
 * for the loopback data/urgent WebSocket connections.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dataplane$0 from "../../internal/terminal/dataplane/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serialport$0 from "../../internal/terminal/serialport/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ymodem$0 from "../../internal/terminal/ymodem/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bootstrap returns the route credentials the renderer needs to attach its
 * data/urgent WebSockets for a session.
 * @param {string} sessionID
 * @returns {$CancellablePromise<dataplane$0.RouteBootstrap>}
 */
export function Bootstrap(sessionID) {
    return $Call.ByID(2388013009, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CancelZmodem honours the existing CRC/safety cancellation boundary. A
 * cancellation is only meaningful for a live receiver, so it is reported as a
 * no-op success when nothing is in flight rather than as a spurious failure.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CancelZmodem(sessionID) {
    return $Call.ByID(2146045067, sessionID);
}

/**
 * Close tears the PTY, transport and data plane route down.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function Close(sessionID) {
    return $Call.ByID(3052890075, sessionID);
}

/**
 * Connect dials SSH, authenticates, opens a PTY shell and starts streaming
 * output into the data plane. It returns the session ID; call Bootstrap to
 * get the route credentials for the renderer WebSocket.
 * @param {$models.SSHConnectRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function Connect(request) {
    return $Call.ByID(4197416449, request);
}

/**
 * @returns {$CancellablePromise<$models.DiscoveredShell[]>}
 */
export function DiscoverShells() {
    return $Call.ByID(2771791745).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultShell() {
    return $Call.ByID(2641412138);
}

/**
 * @param {$models.DockerStatsOptions} options
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function GetDockerStats(options) {
    return $Call.ByID(612413738, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetExitStatus is the reliable side channel for binary Complete frames. Records
 * are published before route teardown and bounded to the last 256 exits.
 * @param {string} id
 * @returns {$CancellablePromise<$models.TerminalExitStatus | null>}
 */
export function GetExitStatus(id) {
    return $Call.ByID(222198297, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.HelperSessionState>}
 */
export function GetHelperSessionState(sessionID) {
    return $Call.ByID(796067590, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function GetServerStats(sessionID) {
    return $Call.ByID(2973806447, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {$models.TerminalPwdOptions} options
 * @returns {$CancellablePromise<$models.TerminalPwdResult>}
 */
export function GetSessionPwd(sessionID, options) {
    return $Call.ByID(1679513552, sessionID, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.TerminalRemoteInfo>}
 */
export function GetSessionRemoteInfo(sessionID) {
    return $Call.ByID(3844699739, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetTelnetEchoMode reports whether the server currently echoes input.
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetTelnetEchoMode(sessionID) {
    return $Call.ByID(2459092297, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ListAutocompleteDirectory uses a separate SFTP channel on the terminal's
 * authenticated transport. It never writes to the interactive shell.
 * @param {string} sessionID
 * @param {string} directory
 * @param {boolean} foldersOnly
 * @param {string} prefix
 * @param {number} limit
 * @returns {$CancellablePromise<$models.AutocompleteDirectoryResult>}
 */
export function ListAutocompleteDirectory(sessionID, directory, foldersOnly, prefix, limit) {
    return $Call.ByID(1485152420, sessionID, directory, foldersOnly, prefix, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListDockerContainers(sessionID) {
    return $Call.ByID(3885403661, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListDockerImages(sessionID) {
    return $Call.ByID(1903017463, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListSerialPorts enumerates OS serial devices.
 * @returns {$CancellablePromise<serialport$0.Info[]>}
 */
export function ListSerialPorts() {
    return $Call.ByID(663993127).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListSystemProcesses(sessionID) {
    return $Call.ByID(3602454473, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListTmuxSessions(sessionID) {
    return $Call.ByID(3524218066, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListenAddr exposes the bound loopback data plane address (host:port).
 * @returns {$CancellablePromise<string>}
 */
export function ListenAddr() {
    return $Call.ByID(305533821);
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ProbeSystemCapabilities(sessionID) {
    return $Call.ByID(2006892894, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ReceiveSerialYmodem downloads files from the serial peer into destinationDir.
 * @param {string} sessionID
 * @param {string} destinationDir
 * @returns {$CancellablePromise<ymodem$0.ReceiveResult[]>}
 */
export function ReceiveSerialYmodem(sessionID, destinationDir) {
    return $Call.ByID(3045917549, sessionID, destinationDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * ReceiveZmodem refuses existing targets; transfer bytes are written only after
 * validated metadata, and partial files are removed if negotiation fails.
 * @param {string} sessionID
 * @param {string} destinationDir
 * @returns {$CancellablePromise<void>}
 */
export function ReceiveZmodem(sessionID, destinationDir) {
    return $Call.ByID(3664406058, sessionID, destinationDir);
}

/**
 * Reconnect rotates only the renderer route. Native Mosh/ET processes retain
 * their protocol keys and roaming state; no new remote server is bootstrapped.
 * @param {string} sessionID
 * @returns {$CancellablePromise<dataplane$0.RouteBootstrap>}
 */
export function Reconnect(sessionID) {
    return $Call.ByID(2144418350, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Resize updates the remote PTY window size.
 * @param {string} sessionID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(sessionID, cols, rows) {
    return $Call.ByID(270758441, sessionID, cols, rows);
}

/**
 * RespondKeyboardInteractive completes or cancels a pending MFA challenge.
 * @param {string} requestID
 * @param {string[]} responses
 * @param {boolean} cancelled
 * @returns {$CancellablePromise<void>}
 */
export function RespondKeyboardInteractive(requestID, responses, cancelled) {
    return $Call.ByID(547631165, requestID, responses, cancelled);
}

/**
 * RestartHelper relaunches the supervised helper inside the same terminal
 * session after a "failed" lifecycle event. The follow-up "running" event
 * arrives through the existing lifecycle callback. Rejected for closing or
 * missing sessions and for helpers whose run loop is still alive.
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.HelperSessionState>}
 */
export function RestartHelper(sessionID) {
    return $Call.ByID(2694891548, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * SendSerialYmodem uploads the file at filePath over the session's serial port
 * using the YMODEM block protocol.
 * @param {string} sessionID
 * @param {string} filePath
 * @returns {$CancellablePromise<ymodem$0.SendResult>}
 */
export function SendSerialYmodem(sessionID, filePath) {
    return $Call.ByID(4074171664, sessionID, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * SendZmodem holds the session's raw byte stream until the peer acknowledges
 * completion. The native terminal writer is shared by data and protocol replies.
 * @param {string} sessionID
 * @param {string} filePath
 * @param {string} remoteName
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function SendZmodem(sessionID, filePath, remoteName, command) {
    return $Call.ByID(695933495, sessionID, filePath, remoteName, command);
}

/**
 * Signal delivers a POSIX signal name (e.g. "KILL") to the remote shell.
 * @param {string} sessionID
 * @param {string} signal
 * @returns {$CancellablePromise<void>}
 */
export function Signal(sessionID, signal) {
    return $Call.ByID(4236247009, sessionID, signal);
}

/**
 * StartEt runs the Eternal Terminal bootstrap. ET uses the same supervised
 * process model; the remote command differs but the local supervision and
 * data-plane wiring are identical to Mosh.
 * @param {$models.MoshStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartEt(request) {
    return $Call.ByID(2928365382, request);
}

/**
 * StartLocal launches a local PTY and streams it on the same data plane as SSH.
 * @param {string} shell
 * @param {string} cwd
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<string>}
 */
export function StartLocal(shell, cwd, cols, rows) {
    return $Call.ByID(3430581078, shell, cwd, cols, rows);
}

/**
 * @param {$models.LocalStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartLocalWithOptions(request) {
    return $Call.ByID(4092120380, request);
}

/**
 * StartMosh runs the mosh bootstrap over SSH and supervises the local
 * mosh-client. The remote handshake scrapes the MOSH CONNECT line, then the
 * client process streams through the same data plane as other sessions.
 * @param {$models.MoshStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartMosh(request) {
    return $Call.ByID(2465988376, request);
}

/**
 * StartSerial opens a serial port and streams bytes onto the data plane.
 * @param {$models.SerialStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartSerial(request) {
    return $Call.ByID(2462094395, request);
}

/**
 * StartTelnet dials a Telnet host and streams IAC-decoded data onto the same
 * data plane as SSH/local PTY. Echo mode transitions are surfaced as events so
 * the renderer can disable local echo when the server takes over; when
 * auto-login is requested the prompt exchange runs against the live stream.
 * @param {$models.TelnetStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartTelnet(request) {
    return $Call.ByID(3093898707, request);
}

/**
 * @param {string} path
 * @param {string} kind
 * @returns {$CancellablePromise<$models.PathValidation>}
 */
export function ValidatePath(path, kind) {
    return $Call.ByID(1211764756, path, kind).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * Write sends raw stdin bytes to the remote shell.
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<number>}
 */
export function Write(sessionID, data) {
    return $Call.ByID(371925220, sessionID, data);
}

// Private type creation functions
const $$createType0 = dataplane$0.RouteBootstrap.createFrom;
const $$createType1 = $models.DiscoveredShell.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.MonitoringResult.createFrom;
const $$createType4 = $models.TerminalExitStatus.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.HelperSessionState.createFrom;
const $$createType7 = $models.TerminalPwdResult.createFrom;
const $$createType8 = $models.TerminalRemoteInfo.createFrom;
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = $models.AutocompleteDirectoryResult.createFrom;
const $$createType11 = serialport$0.Info.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = ymodem$0.ReceiveResult.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = ymodem$0.SendResult.createFrom;
const $$createType16 = $models.PathValidation.createFrom;
