// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService owns SSH terminal sessions end-to-end: SSH dial → auth →
 * PTY channel → data plane streaming → renderer WebSocket. Each session gets
 * a route bootstrap (generation + one-use tokens) that the renderer exchanges
 * for the loopback data/urgent WebSocket connections.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dataplane$0 from "../../internal/terminal/dataplane/models.js";

/**
 * Bootstrap returns the route credentials the renderer needs to attach its
 * data/urgent WebSockets for a session.
 * @param {string} sessionID
 * @returns {$CancellablePromise<dataplane$0.RouteBootstrap>}
 */
export function Bootstrap(sessionID) {
    return $Call.ByID(2388013009, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Close tears the PTY, transport and data plane route down.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function Close(sessionID) {
    return $Call.ByID(3052890075, sessionID);
}

/**
 * Connect dials SSH, authenticates, opens a PTY shell and starts streaming
 * output into the data plane. It returns the session ID; call Bootstrap to
 * get the route credentials for the renderer WebSocket.
 * @param {string} host
 * @param {number} port
 * @param {string} username
 * @param {string} password
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<string>}
 */
export function Connect(host, port, username, password, cols, rows) {
    return $Call.ByID(4197416449, host, port, username, password, cols, rows);
}

/**
 * ListenAddr exposes the bound loopback data plane address (host:port).
 * @returns {$CancellablePromise<string>}
 */
export function ListenAddr() {
    return $Call.ByID(305533821);
}

/**
 * Resize updates the remote PTY window size.
 * @param {string} sessionID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(sessionID, cols, rows) {
    return $Call.ByID(270758441, sessionID, cols, rows);
}

/**
 * Signal delivers a POSIX signal name (e.g. "KILL") to the remote shell.
 * @param {string} sessionID
 * @param {string} signal
 * @returns {$CancellablePromise<void>}
 */
export function Signal(sessionID, signal) {
    return $Call.ByID(4236247009, sessionID, signal);
}

/**
 * Write sends raw stdin bytes to the remote shell.
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<number>}
 */
export function Write(sessionID, data) {
    return $Call.ByID(371925220, sessionID, data);
}

// Private type creation functions
const $$createType0 = dataplane$0.RouteBootstrap.createFrom;
