// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrayService owns the tray context menu and rebuilds it whenever the
 * renderer reports a new appearance language.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Quit terminates the application process (not merely hiding the window).
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(3411543682);
}

/**
 * SetLanguage switches the tray menu language and rebuilds it in place.
 * @param {string} language
 * @returns {$CancellablePromise<boolean>}
 */
export function SetLanguage(language) {
    return $Call.ByID(71540681, language);
}
