// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpgradeService drives the Electron N-1 → Wails upgrade bootstrap chain
 * (P6-04): detect → backup → migrate → verify → activate, persisted
 * crash-safely in the profile data directory. The service itself is
 * stateless; every call reopens the persisted coordinator so renderer
 * reloads cannot desynchronize the machine.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Advance moves the machine one step forward.
 * @param {string} fromVersion
 * @param {string} toVersion
 * @param {string} next
 * @returns {$CancellablePromise<$models.UpgradeStatus>}
 */
export function Advance(fromVersion, toVersion, next) {
    return $Call.ByID(3409660517, fromVersion, toVersion, next).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Begin starts (or resumes) the upgrade sequence for the version pair.
 * @param {string} fromVersion
 * @param {string} toVersion
 * @returns {$CancellablePromise<$models.UpgradeStatus>}
 */
export function Begin(fromVersion, toVersion) {
    return $Call.ByID(2283065526, fromVersion, toVersion).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Cancel discards the persisted sequence (rollback to the Electron carrier).
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(1118840355);
}

/**
 * Status reports the persisted upgrade sequence; the returned status carries
 * empty From/To and a "detected" step when no upgrade is in flight.
 * @returns {$CancellablePromise<$models.UpgradeStatus>}
 */
export function Status() {
    return $Call.ByID(2146682391).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.UpgradeStatus.createFrom;
