package zmodem

import (
	"bytes"
	"context"
	"encoding/hex"
	"errors"
	"io"
	"testing"
)

func TestIndependentCRC32Fixture(t *testing.T) {
	// Generated by zmodem.js, not this package's encoder.
	fixture, err := hex.DecodeString("2a1843184a1840184018401840bcef18d218cc61626318683a18c134e4")
	if err != nil {
		t.Fatal(err)
	}
	var got []byte
	r := &Receiver{OnChunk: func(b []byte) error { got = append(got, b...); return nil }}
	wire := append(framedUnit(ZFILE, []byte("safe.bin\x003\x00")), fixture...)
	wire = append(wire, hexHeader(ZEOF, 3)...)
	for _, b := range wire {
		if _, err := r.FeedSession(context.Background(), []byte{b}); err != nil {
			t.Fatal(err)
		}
	}
	if string(got) != "abc" {
		t.Fatalf("%q", got)
	}
}

func TestRawPeerCancellationAcrossReads(t *testing.T) {
	r := &Receiver{}
	for i := 0; i < 4; i++ {
		if _, err := r.FeedSession(context.Background(), []byte{ZDLE}); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := r.FeedSession(context.Background(), []byte{ZDLE}); !errors.Is(err, ErrCancelled) {
		t.Fatalf("CAN burst: %v", err)
	}
}
func TestCorruptDataNeverReachesSink(t *testing.T) {
	called := false
	r := &Receiver{OnChunk: func([]byte) error { called = true; return nil }}
	wire := append(framedUnit(ZFILE, []byte("safe.bin\x003\x00")), binaryHeader(ZDATA, 0)...)
	packet := dataPacket([]byte("abc"), zcrce)
	packet[0] ^= 1
	wire = append(wire, packet...)
	if _, err := r.FeedSession(context.Background(), wire); !errors.Is(err, ErrCRCMismatch) {
		t.Fatal(err)
	}
	if called {
		t.Fatal("corrupt bytes reached sink")
	}
}
func TestIncompleteFileNeverCompletes(t *testing.T) {
	for _, suffix := range [][]byte{hexHeader(ZEOF, 0), hexHeader(ZFIN, 0)} {
		r := &Receiver{}
		wire := append(framedUnit(ZFILE, []byte("safe.bin\x003\x00")), suffix...)
		if _, err := r.FeedSession(context.Background(), wire); !errors.Is(err, ErrFrameMalformed) {
			t.Fatal(err)
		}
	}
	r := &Receiver{}
	if err := r.SessionReader(context.Background(), bytes.NewReader(framedUnit(ZFILE, []byte("safe.bin\x003\x00")))); !errors.Is(err, io.ErrUnexpectedEOF) {
		t.Fatal(err)
	}
}
func TestSenderOnlyReportsAcknowledgedProgress(t *testing.T) {
	for _, good := range []bool{false, true} {
		var replies []byte
		replies = append(replies, hexHeader(ZRINIT, 0)...)
		replies = append(replies, hexHeader(ZRPOS, 0)...)
		ack := uint32(2)
		if good {
			ack = 3
		}
		replies = append(replies, hexHeader(ZACK, ack)...)
		replies = append(replies, hexHeader(ZRINIT, 0)...)
		replies = append(replies, hexHeader(ZFIN, 0)...)
		reader := bytes.NewReader(replies)
		var progress int64
		s := &Sender{Write: func([]byte) error { return nil }, Read: func(_ context.Context, b []byte) (int, error) { return reader.Read(b) }, OnProgress: func(n, total int64) {
			if total != 3 {
				t.Fatal(total)
			}
			progress = n
		}}
		err := s.SendFile(context.Background(), FileMeta{Name: "safe.bin"}, []byte("abc"))
		if good {
			if err != nil || progress != 3 {
				t.Fatalf("%v progress=%d", err, progress)
			}
		} else if !errors.Is(err, ErrFrameMalformed) || progress != 0 {
			t.Fatalf("%v progress=%d", err, progress)
		}
	}
}
func TestSenderCancellationWritesCAN(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	var wire []byte
	s := &Sender{Write: func(b []byte) error { wire = append(wire, b...); return nil }, Read: func(context.Context, []byte) (int, error) { t.Fatal("read after cancel"); return 0, nil }}
	if err := s.SendFile(ctx, FileMeta{Name: "safe.bin"}, nil); !errors.Is(err, ErrCancelled) {
		t.Fatal(err)
	}
	if !bytes.HasPrefix(wire, bytes.Repeat([]byte{ZDLE}, 5)) {
		t.Fatal("missing CAN burst")
	}
}
