// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Schema is the root declarative UI definition for one plugin.
 */
export class Schema {
    /**
     * Creates a new Schema instance.
     * @param {Partial<Schema>} [$$source = {}] - The source object to create the Schema.
     */
    constructor($$source = {}) {
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {SettingField[]}
             */
            this["settings"] = [];
        }
        if (!("views" in $$source)) {
            /**
             * @member
             * @type {ViewDef[]}
             */
            this["views"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Schema instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Schema}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField0_0($$parsedSource["settings"]);
        }
        if ("views" in $$parsedSource) {
            $$parsedSource["views"] = $$createField1_0($$parsedSource["views"]);
        }
        return new Schema(/** @type {Partial<Schema>} */($$parsedSource));
    }
}

/**
 * SettingField is one form field.
 */
export class SettingField {
    /**
     * Creates a new SettingField instance.
     * @param {Partial<SettingField>} [$$source = {}] - The source object to create the SettingField.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "text" | "number" | "boolean" | "select" | "password"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["default"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * for select
             * @member
             * @type {string[] | undefined}
             */
            this["options"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["required"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingField}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new SettingField(/** @type {Partial<SettingField>} */($$parsedSource));
    }
}

/**
 * ViewDef is one declarative view.
 */
export class ViewDef {
    /**
     * Creates a new ViewDef instance.
     * @param {Partial<ViewDef>} [$$source = {}] - The source object to create the ViewDef.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "list" | "card"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * for list
             * @member
             * @type {string[] | undefined}
             */
            this["columns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * data bindings
             * @member
             * @type {string[] | undefined}
             */
            this["bindings"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ViewDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ViewDef}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField3_0($$parsedSource["columns"]);
        }
        if ("bindings" in $$parsedSource) {
            $$parsedSource["bindings"] = $$createField4_0($$parsedSource["bindings"]);
        }
        return new ViewDef(/** @type {Partial<ViewDef>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SettingField.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ViewDef.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
