// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LocalEntry matches the renderer's local directory listing contract.
 */
export class LocalEntry {
    /**
     * Creates a new LocalEntry instance.
     * @param {Partial<LocalEntry>} [$$source = {}] - The source object to create the LocalEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["size"] = "";
        }
        if (!("lastModified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastModified"] = "";
        }
        if (!("linkTarget" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["linkTarget"] = null;
        }
        if (!("hidden" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalEntry(/** @type {Partial<LocalEntry>} */($$parsedSource));
    }
}
