// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    AgentEventEnvelope,
    EventPage,
    PrepareTurnRequest,
    PreparedTurn,
    TurnCommand,
    TurnCommandKind,
    TurnInput,
    TurnScope,
    TurnSnapshot
} from "./models.js";

import * as $models from "./models.js";

/**
 * AgentID identifies one agent kind or adapter.
 * @typedef {$models.AgentID} AgentID
 */

/**
 * ChatSessionID identifies one AI chat session.
 * @typedef {$models.ChatSessionID} ChatSessionID
 */

/**
 * InstanceID identifies one running application instance.
 * @typedef {$models.InstanceID} InstanceID
 */

/**
 * RequestID correlates one request/response pair.
 * @typedef {$models.RequestID} RequestID
 */

/**
 * TurnID identifies one prepared or running AI turn.
 * @typedef {$models.TurnID} TurnID
 */
