// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ReceiveResult reports one received file.
 */
export class ReceiveResult {
    /**
     * Creates a new ReceiveResult instance.
     * @param {Partial<ReceiveResult>} [$$source = {}] - The source object to create the ReceiveResult.
     */
    constructor($$source = {}) {
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }
        if (!("writtenBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["writtenBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReceiveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReceiveResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReceiveResult(/** @type {Partial<ReceiveResult>} */($$parsedSource));
    }
}

/**
 * SendResult reports a completed send.
 */
export class SendResult {
    /**
     * Creates a new SendResult instance.
     * @param {Partial<SendResult>} [$$source = {}] - The source object to create the SendResult.
     */
    constructor($$source = {}) {
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }
        if (!("writtenBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["writtenBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendResult(/** @type {Partial<SendResult>} */($$parsedSource));
    }
}
