// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    AutocompleteDirectoryEntry,
    AutocompleteDirectoryResult,
    DiscoveredShell,
    DockerStatsOptions,
    HelperSessionState,
    LocalStartRequest,
    MonitoringResult,
    MoshStartRequest,
    PathValidation,
    ProxyProbeRequest,
    ProxyProbeResult,
    SSHConnectRequest,
    SerialStartRequest,
    TelnetStartRequest,
    TerminalExitStatus,
    TerminalPwdOptions,
    TerminalPwdResult,
    TerminalRemoteInfo
} from "./models.js";

import * as $models from "./models.js";

/**
 * CommandRunner executes one command bound to a session's transport and
 * reports the outcome. known is false when the run ended without an
 * observable exit status.
 * @typedef {$models.CommandRunner} CommandRunner
 */
