// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const Kind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * listen local, tunnel to target via SSH
     */
    KindLocal: "local",

    /**
     * ask SSH server to listen, forward to local target
     */
    KindRemote: "remote",

    /**
     * local SOCKS5 proxy through SSH
     */
    KindDynamic: "dynamic",
};

export class Spec {
    /**
     * Creates a new Spec instance.
     * @param {Partial<Spec>} [$$source = {}] - The source object to create the Spec.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {Kind}
             */
            this["kind"] = Kind.$zero;
        }
        if (!("bindHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bindHost"] = "";
        }
        if (!("bindPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bindPort"] = 0;
        }
        if (!("targetHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetHost"] = "";
        }
        if (!("targetPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["targetPort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Spec instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Spec}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Spec(/** @type {Partial<Spec>} */($$parsedSource));
    }
}

export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("spec" in $$source)) {
            /**
             * @member
             * @type {Spec}
             */
            this["spec"] = (new Spec());
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("activeConnections" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeConnections"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("spec" in $$parsedSource) {
            $$parsedSource["spec"] = $$createField0_0($$parsedSource["spec"]);
        }
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Spec.createFrom;
