// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Mutation is one key operation inside a transaction.
 * @typedef {Object} Mutation
 * @property {string} Domain
 * @property {string} Key
 * @property {string | null} Value
 * @property {boolean} Delete
 */

/**
 * WriteResult reports the post-commit state.
 * @typedef {Object} WriteResult
 * @property {number} Revision
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
