// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * HealthStatus is the liveness payload used by shells and CI smokes.
 * @typedef {$models.HealthStatus} HealthStatus
 */

/**
 * VersionInfo describes the running application build.
 * @typedef {$models.VersionInfo} VersionInfo
 */

/**
 * WindowRoleInfo describes a resolved window role.
 * @typedef {$models.WindowRoleInfo} WindowRoleInfo
 */
