// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HealthStatus is the liveness payload used by shells and CI smokes.
 * @typedef {Object} HealthStatus
 * @property {string} status
 * @property {number} pid
 */

/**
 * VersionInfo describes the running application build.
 * @typedef {Object} VersionInfo
 * @property {string} name
 * @property {string} version
 * @property {string} goos
 * @property {string} goarch
 * @property {string} goVersion
 */

/**
 * WindowRoleInfo describes a resolved window role.
 * @typedef {Object} WindowRoleInfo
 * @property {string} role
 * @property {boolean} singleInstance
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
