// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Client
} from "./models.js";

import * as $models from "./models.js";

/**
 * Conn represents an SSH connection for both server and client roles.
 * Conn is the basis for implementing an application layer, such
 * as ClientConn, which implements the traditional shell access for
 * clients.
 * @typedef {$models.Conn} Conn
 */
