// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Client implements a traditional SSH client that supports shells,
 * subprocesses, TCP port/streamlocal forwarding and tunneled dialing.
 */
export class Client {
    /**
     * Creates a new Client instance.
     * @param {Partial<Client>} [$$source = {}] - The source object to create the Client.
     */
    constructor($$source = {}) {
        if (!("Conn" in $$source)) {
            /**
             * @member
             * @type {Conn}
             */
            this["Conn"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Client instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Client}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Client(/** @type {Partial<Client>} */($$parsedSource));
    }
}

/**
 * Conn represents an SSH connection for both server and client roles.
 * Conn is the basis for implementing an application layer, such
 * as ClientConn, which implements the traditional shell access for
 * clients.
 * @typedef {any} Conn
 */
