// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Progress is the aggregated progress snapshot. UI subscribes to snapshots at
 * a bounded rate — never per chunk — so Wails events are not flooded.
 */
export class Progress {
    /**
     * Creates a new Progress instance.
     * @param {Partial<Progress>} [$$source = {}] - The source object to create the Progress.
     */
    constructor($$source = {}) {
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = State.$zero;
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }
        if (!("doneBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["doneBytes"] = 0;
        }
        if (!("chunksDone" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunksDone"] = 0;
        }
        if (!("chunksTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunksTotal"] = 0;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Progress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Progress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Progress(/** @type {Partial<Progress>} */($$parsedSource));
    }
}

/**
 * State is the task lifecycle state.
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatePending: "pending",
    StateRunning: "running",
    StatePaused: "paused",
    StateCompleted: "completed",
    StateCancelled: "cancelled",
    StateFailed: "failed",
};

/**
 * TaskSpec describes one transfer.
 */
export class TaskSpec {
    /**
     * Creates a new TaskSpec instance.
     * @param {Partial<TaskSpec>} [$$source = {}] - The source object to create the TaskSpec.
     */
    constructor($$source = {}) {
        if (!("TaskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TaskID"] = "";
        }
        if (!("HostKey" in $$source)) {
            /**
             * per-host concurrency scope (endpoint identity)
             * @member
             * @type {string}
             */
            this["HostKey"] = "";
        }
        if (!("SourcePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SourcePath"] = "";
        }
        if (!("SinkPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SinkPath"] = "";
        }
        if (!("TotalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TotalBytes"] = 0;
        }
        if (!("ChunkSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ChunkSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskSpec instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskSpec}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskSpec(/** @type {Partial<TaskSpec>} */($$parsedSource));
    }
}
