// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ListItem is one active tunnel row.
 */
export class ListItem {
    /**
     * Creates a new ListItem instance.
     * @param {Partial<ListItem>} [$$source = {}] - The source object to create the ListItem.
     */
    constructor($$source = {}) {
        if (!("ruleId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ruleId"] = "";
        }
        if (!("tunnelId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnelId"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListItem(/** @type {Partial<ListItem>} */($$parsedSource));
    }
}

/**
 * Result is one tunnel operation outcome.
 */
export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("tunnelId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnelId"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["cancelled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["blockedByCleanup"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["reused"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}

/**
 * RuntimeRecord is one row of a RuntimeSnapshot.
 */
export class RuntimeRecord {
    /**
     * Creates a new RuntimeRecord instance.
     * @param {Partial<RuntimeRecord>} [$$source = {}] - The source object to create the RuntimeRecord.
     */
    constructor($$source = {}) {
        if (!("ruleId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ruleId"] = "";
        }
        if (!("tunnelId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnelId"] = "";
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeRecord(/** @type {Partial<RuntimeRecord>} */($$parsedSource));
    }
}

/**
 * RuntimeSnapshot is the renderer-facing forward table state.
 */
export class RuntimeSnapshot {
    /**
     * Creates a new RuntimeSnapshot instance.
     * @param {Partial<RuntimeSnapshot>} [$$source = {}] - The source object to create the RuntimeSnapshot.
     */
    constructor($$source = {}) {
        if (!("epoch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["epoch"] = "";
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("records" in $$source)) {
            /**
             * @member
             * @type {RuntimeRecord[]}
             */
            this["records"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("records" in $$parsedSource) {
            $$parsedSource["records"] = $$createField2_0($$parsedSource["records"]);
        }
        return new RuntimeSnapshot(/** @type {Partial<RuntimeSnapshot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = RuntimeRecord.createFrom;
const $$createType1 = $Create.Array($$createType0);
