// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filesystem$0 from "../../internal/platform/filesystem/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.TempClearResult>}
 */
export function ClearTemp() {
    return $Call.ByID(571030481).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteChatToolOutputsTemp removes every spill file owned by one chat.
 * @param {string} chatSessionID
 * @returns {$CancellablePromise<$models.ToolOutputDeleteManyResult>}
 */
export function DeleteChatToolOutputsTemp(chatSessionID) {
    return $Call.ByID(3701132131, chatSessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @param {string} expectedType
 * @returns {$CancellablePromise<void>}
 */
export function DeletePath(path, expectedType) {
    return $Call.ByID(2395507066, path, expectedType);
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTempFile(filePath) {
    return $Call.ByID(2672759029, filePath);
}

/**
 * DeleteTerminalToolOutputsEverywhereTemp removes spill files for a terminal
 * session across every chat.
 * @param {string} terminalSessionID
 * @returns {$CancellablePromise<$models.ToolOutputDeleteManyResult>}
 */
export function DeleteTerminalToolOutputsEverywhereTemp(terminalSessionID) {
    return $Call.ByID(1379560263, terminalSessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteTerminalToolOutputsTemp removes spill files for one chat+terminal
 * pair.
 * @param {string} chatSessionID
 * @param {string} terminalSessionID
 * @returns {$CancellablePromise<$models.ToolOutputDeleteManyResult>}
 */
export function DeleteTerminalToolOutputsTemp(chatSessionID, terminalSessionID) {
    return $Call.ByID(438647725, chatSessionID, terminalSessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteToolOutputTemp removes one spill file. Paths outside the managed
 * tool-output directory are rejected; a missing file deletes successfully.
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.ToolOutputDeleteResult>}
 */
export function DeleteToolOutputTemp(filePath) {
    return $Call.ByID(3039170524, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} archivePath
 * @param {string} destinationRoot
 * @returns {$CancellablePromise<number>}
 */
export function ExtractArchive(archivePath, destinationRoot) {
    return $Call.ByID(3240863779, archivePath, destinationRoot);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function HomeDir() {
    return $Call.ByID(1121754232);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<filesystem$0.LocalEntry[]>}
 */
export function ListDir(path) {
    return $Call.ByID(729165017, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListDrives() {
    return $Call.ByID(3979334175).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.LocalFileInfo>}
 */
export function Lstat(path) {
    return $Call.ByID(2915506260, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Mkdir(path) {
    return $Call.ByID(3152918341, path);
}

/**
 * OpenPath opens a file or directory with the system default handler. Unlike
 * OpenWithSystemDefault it also accepts directories: the SFTP panel reveals a
 * completed transfer's target folder by opening its parent path.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenPath(path) {
    return $Call.ByID(2345953741, path);
}

/**
 * @param {string} filePath
 * @param {string} appPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenWithApplication(filePath, appPath) {
    return $Call.ByID(247617680, filePath, appPath);
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function OpenWithSystemDefault(filePath) {
    return $Call.ByID(2875809596, filePath);
}

/**
 * ReadClipboardImage uses the OS because Wails Clipboard only exposes text.
 * @returns {$CancellablePromise<$models.ClipboardImageFile | null>}
 */
export function ReadClipboardImage() {
    return $Call.ByID(1323029781).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ReadFile returns a bounded local file payload. A non-positive maxBytes uses
 * the editor's existing 64 MiB desktop ceiling.
 * @param {string} path
 * @param {number} maxBytes
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path, maxBytes) {
    return $Call.ByID(932756824, path, maxBytes).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * ReadToolOutputTemp serves one bounded read of a persisted spill file with
 * the same head/tail/range/full/search semantics as the in-memory store.
 * Corrupt or missing files return null; only path escapes are hard errors.
 * @param {string} filePath
 * @param {$models.ToolOutputReadRequest | null} request
 * @returns {$CancellablePromise<$models.ToolOutputReadPayload | null>}
 */
export function ReadToolOutputTemp(filePath, request) {
    return $Call.ByID(1413788311, filePath, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ReleaseTempFile ends renderer ownership without removing an external-edit
 * download. Call after the last consumer finishes; transfer I/O has its own pin.
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function ReleaseTempFile(filePath) {
    return $Call.ByID(4145957983, filePath);
}

/**
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function RenamePath(oldPath, newPath) {
    return $Call.ByID(3929756967, oldPath, newPath);
}

/**
 * RestoreToolOutputTemp looks up one persisted handle for a chat session.
 * Missing, corrupt, or foreign records return null (not an error) so the
 * renderer treats the handle simply as unrestorable.
 * @param {string} handleID
 * @param {string} chatSessionID
 * @returns {$CancellablePromise<$models.ToolOutputRestoredRecord | null>}
 */
export function RestoreToolOutputTemp(handleID, chatSessionID) {
    return $Call.ByID(3675899777, handleID, chatSessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * StageAppend writes one base64-decoded chunk at offset. []byte bindings
 * arrive base64-encoded through the Wails transport.
 * @param {string} tempPath
 * @param {number} offset
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function StageAppend(tempPath, offset, data) {
    return $Call.ByID(398939544, tempPath, offset, data);
}

/**
 * StageBegin creates a temp file for a renderer-staged upload and returns
 * its path. The renderer streams chunks via StageAppend.
 * @param {string} fileName
 * @returns {$CancellablePromise<string>}
 */
export function StageBegin(fileName) {
    return $Call.ByID(3961908005, fileName);
}

/**
 * StageDiscard removes a staged temp file. Only LemonSSH staging files are
 * eligible so a renderer cannot delete arbitrary paths.
 * @param {string} tempPath
 * @returns {$CancellablePromise<void>}
 */
export function StageDiscard(tempPath) {
    return $Call.ByID(3485451546, tempPath);
}

/**
 * StageFromLocalPath copies one local file into the LemonSSH staging temp
 * directory in a single call (stat → open → copy with no renderer round trip
 * in between), so transient drag sources and path quirks cannot race the
 * upload. Returns the staged temp path and original size.
 * @param {string} path
 * @returns {$CancellablePromise<[string, number]>}
 */
export function StageFromLocalPath(path) {
    return $Call.ByID(1820087868, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.LocalFileInfo>}
 */
export function Stat(path) {
    return $Call.ByID(3714331452, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * StatPath stats one local path (read-only) so dropped files can be
 * classified before upload.
 * @param {string} path
 * @returns {$CancellablePromise<$models.LocalPathStat>}
 */
export function StatPath(path) {
    return $Call.ByID(1999196219, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.LocalSystemInfo>}
 */
export function SystemInfo() {
    return $Call.ByID(1771393923).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function TempFilePath(name) {
    return $Call.ByID(3262733025, name);
}

/**
 * @returns {$CancellablePromise<$models.TempDirectoryInfo>}
 */
export function TempInfo() {
    return $Call.ByID(3758389736).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ToolOutputPersistenceStatus reports whether the dedicated temp service is
 * wired; the renderer gates spill and restore on this.
 * @returns {$CancellablePromise<$models.ToolOutputPersistenceStatusResult>}
 */
export function ToolOutputPersistenceStatus() {
    return $Call.ByID(360384890).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function ValidateTempFile(filePath) {
    return $Call.ByID(3295034776, filePath);
}

/**
 * WriteFile writes renderer-provided bytes to a local file without following
 * a final symlink. Parent directories must already exist.
 * @param {string} path
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(path, data) {
    return $Call.ByID(2971061639, path, data);
}

/**
 * WriteToolOutputTemp stores one record plus content in the managed temp
 * directory and returns the managed path. The write lands via a same-name
 * .tmp file and rename so a crash cannot leave a half-written envelope
 * behind under the final name.
 * @param {$models.ToolOutputRecord} record
 * @param {string} content
 * @returns {$CancellablePromise<$models.ToolOutputWriteResult>}
 */
export function WriteToolOutputTemp(record, content) {
    return $Call.ByID(285708604, record, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.TempClearResult.createFrom;
const $$createType1 = $models.ToolOutputDeleteManyResult.createFrom;
const $$createType2 = $models.ToolOutputDeleteResult.createFrom;
const $$createType3 = filesystem$0.LocalEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $models.LocalFileInfo.createFrom;
const $$createType7 = $models.ClipboardImageFile.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.ToolOutputReadPayload.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.ToolOutputRestoredRecord.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $models.LocalPathStat.createFrom;
const $$createType14 = $models.LocalSystemInfo.createFrom;
const $$createType15 = $models.TempDirectoryInfo.createFrom;
const $$createType16 = $models.ToolOutputPersistenceStatusResult.createFrom;
const $$createType17 = $models.ToolOutputWriteResult.createFrom;
