// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileWatchService is the Wails-facing external-edit sync-back service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListFileWatches returns the active watches for diagnostics.
 * @returns {$CancellablePromise<$models.FileWatchSummary[]>}
 */
export function ListFileWatches() {
    return $Call.ByID(2683883893).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RegisterTempFile records a renderer-owned external-edit download so session
 * cleanup can delete it even when auto-sync was disabled. Refcounted: parallel
 * editors of the same download each register once.
 * @param {string} sftpID
 * @param {string} localPath
 * @returns {$CancellablePromise<$models.FileWatchResult>}
 */
export function RegisterTempFile(sftpID, localPath) {
    return $Call.ByID(288729913, sftpID, localPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * StartFileWatch watches a managed-temp download and streams every save back
 * to its remote source. Duplicate starts for the same key reuse the watch.
 * @param {string} localPath
 * @param {string} remotePath
 * @param {string} sftpID
 * @param {string} encoding
 * @returns {$CancellablePromise<$models.FileWatchStartResult>}
 */
export function StartFileWatch(localPath, remotePath, sftpID, encoding) {
    return $Call.ByID(3304428149, localPath, remotePath, sftpID, encoding).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * StopFileWatch stops one watch and optionally deletes its temp download.
 * @param {string} watchID
 * @param {boolean} cleanupTempFile
 * @returns {$CancellablePromise<$models.FileWatchResult>}
 */
export function StopFileWatch(watchID, cleanupTempFile) {
    return $Call.ByID(4118424537, watchID, cleanupTempFile).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UnregisterTempFile releases one renderer reference. The last reference
 * deletes the managed temp download; a still-referenced file is retained.
 * @param {string} sftpID
 * @param {string} localPath
 * @returns {$CancellablePromise<$models.FileWatchUnregisterResult>}
 */
export function UnregisterTempFile(sftpID, localPath) {
    return $Call.ByID(534555438, sftpID, localPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.FileWatchSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.FileWatchResult.createFrom;
const $$createType3 = $models.FileWatchStartResult.createFrom;
const $$createType4 = $models.FileWatchUnregisterResult.createFrom;
