// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig is the pull handshake: configuration cannot race the renderer's
 * event listener, and only the URL-authenticated window identity may read it.
 * @param {string} windowID
 * @param {string} token
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetConfig(windowID, token) {
    return $Call.ByID(1178025213, windowID, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Heartbeat extends the window's lease; a renderer that stops answering
 * (crash/hang) lets it lapse and the window closes itself.
 * @param {string} windowID
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function Heartbeat(windowID, token) {
    return $Call.ByID(3737551103, windowID, token);
}

/**
 * Open creates a peer session window carrying the clone payload (title,
 * sourceSession, localShellType). The payload is stored server-side; the new
 * window pulls it via GetConfig once its renderer is up.
 * @param {{ [_ in string]?: any }} payload
 * @returns {$CancellablePromise<$models.SessionWindowOpenResult>}
 */
export function Open(payload) {
    return $Call.ByID(1643171185, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.SessionWindowOpenResult.createFrom;
