// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService is the Wails-facing facade over internal/app/terminaluse.
 * It owns only shell wiring: renderer event callbacks and service registration.
 * All session rules (SSH dial → auth → PTY → data plane streaming → route
 * bootstrap, telnet/serial/mosh/et starts, exit tracking) live in the shared
 * terminaluse.Service, so a future capability dispatch entry point can call
 * the same instance.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminaluse$0 from "../../internal/app/terminaluse/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dataplane$0 from "../../internal/terminal/dataplane/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serialport$0 from "../../internal/terminal/serialport/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ymodem$0 from "../../internal/terminal/ymodem/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../../../../../golang.org/x/crypto/ssh/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcquireSessionFlowPauseLease pauses renderer-bound output for an attach popup.
 * @param {string} sessionID
 * @returns {$CancellablePromise<terminaluse$0.FlowPauseLease>}
 */
export function AcquireSessionFlowPauseLease(sessionID) {
    return $Call.ByID(1698724209, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ApplySessionSnapshot pushes the popup display state to the home renderer.
 * @param {string} sessionID
 * @param {string} snapshot
 * @param {terminaluse$0.SnapshotContext} context
 * @param {string} authorization
 * @returns {$CancellablePromise<terminaluse$0.ActionResult>}
 */
export function ApplySessionSnapshot(sessionID, snapshot, context, authorization) {
    return $Call.ByID(3664500469, sessionID, snapshot, context, authorization).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<dataplane$0.RouteBootstrap>}
 */
export function Bootstrap(sessionID) {
    return $Call.ByID(2388013009, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CancelZmodem(sessionID) {
    return $Call.ByID(2146045067, sessionID);
}

/**
 * @param {$models.SSHAgentOptions} options
 * @returns {$CancellablePromise<$models.SSHAgentStatus>}
 */
export function CheckSshAgent(options) {
    return $Call.ByID(3260916108, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function Close(sessionID) {
    return $Call.ByID(3052890075, sessionID);
}

/**
 * CloseSession closes any terminal session through the ordinary close path
 * (plugin connections route the close through their plugin hook).
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CloseSession(sessionID) {
    return $Call.ByID(3305403653, sessionID);
}

/**
 * @param {$models.SSHConnectRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function Connect(request) {
    return $Call.ByID(4197416449, request);
}

/**
 * @param {$models.TmuxSessionRequest} request
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function CreateTmuxSession(request) {
    return $Call.ByID(2346936473, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DiscoveredShell[]>}
 */
export function DiscoverShells() {
    return $Call.ByID(2771791745).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {$models.DockerActionRequest} request
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function DockerAction(request) {
    return $Call.ByID(165986671, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.DockerImageActionRequest} request
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function DockerImageAction(request) {
    return $Call.ByID(2638850792, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.DockerInspectRequest} request
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function DockerImageInspect(request) {
    return $Call.ByID(1692815502, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.DockerInspectRequest} request
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function DockerInspect(request) {
    return $Call.ByID(3781119207, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ExecCommand runs one command over a fresh authenticated SSH connection
 * (ssh-copy-id style key export, remote checks) and closes the transport.
 * @param {$models.ExecCommandRequest} request
 * @returns {$CancellablePromise<$models.ExecCommandResult>}
 */
export function ExecCommand(request) {
    return $Call.ByID(4036455965, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {$models.KeyPairOptions} options
 * @returns {$CancellablePromise<$models.KeyPairResult>}
 */
export function GenerateKeyPair(options) {
    return $Call.ByID(1524652637, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DefaultSSHKey[]>}
 */
export function GetDefaultKeys() {
    return $Call.ByID(1930779420).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultShell() {
    return $Call.ByID(2641412138);
}

/**
 * @param {$models.DockerStatsOptions} options
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function GetDockerStats(options) {
    return $Call.ByID(612413738, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.TerminalExitStatus | null>}
 */
export function GetExitStatus(id) {
    return $Call.ByID(222198297, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.HelperSessionState>}
 */
export function GetHelperSessionState(sessionID) {
    return $Call.ByID(796067590, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function GetServerStats(sessionID) {
    return $Call.ByID(2973806447, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetSessionDistroInfo runs the /etc/os-release probe on the session's
 * existing transport (no new SSH connection).
 * @param {string} sessionID
 * @returns {$CancellablePromise<terminaluse$0.SessionDistroResult>}
 */
export function GetSessionDistroInfo(sessionID) {
    return $Call.ByID(2961719782, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetSessionEncoding reports the charset pinned for one session ("" = UTF-8)
 * so any attaching display (popups, re-attach) can decode output correctly.
 * @param {string} sessionID
 * @returns {$CancellablePromise<string>}
 */
export function GetSessionEncoding(sessionID) {
    return $Call.ByID(3305737652, sessionID);
}

/**
 * @param {string} sessionID
 * @param {$models.TerminalPwdOptions} options
 * @returns {$CancellablePromise<$models.TerminalPwdResult>}
 */
export function GetSessionPwd(sessionID, options) {
    return $Call.ByID(1679513552, sessionID, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.TerminalRemoteInfo>}
 */
export function GetSessionRemoteInfo(sessionID) {
    return $Call.ByID(3844699739, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetTelnetEchoMode(sessionID) {
    return $Call.ByID(2459092297, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListAccelerators(sessionID) {
    return $Call.ByID(1247856625, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {string} directory
 * @param {boolean} foldersOnly
 * @param {string} prefix
 * @param {number} limit
 * @returns {$CancellablePromise<$models.AutocompleteDirectoryResult>}
 */
export function ListAutocompleteDirectory(sessionID, directory, foldersOnly, prefix, limit) {
    return $Call.ByID(1485152420, sessionID, directory, foldersOnly, prefix, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListDockerContainers(sessionID) {
    return $Call.ByID(3885403661, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListDockerImages(sessionID) {
    return $Call.ByID(1903017463, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListListeningPorts(sessionID) {
    return $Call.ByID(1107536006, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<serialport$0.Info[]>}
 */
export function ListSerialPorts() {
    return $Call.ByID(663993127).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListSystemProcesses(sessionID) {
    return $Call.ByID(3602454473, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListSystemServices(sessionID) {
    return $Call.ByID(1687033304, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.TmuxTargetRequest} request
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListTmuxClients(request) {
    return $Call.ByID(364471245, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.TmuxTargetRequest} request
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListTmuxPanes(request) {
    return $Call.ByID(4015298154, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListTmuxSessions(sessionID) {
    return $Call.ByID(3524218066, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.TmuxTargetRequest} request
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ListTmuxWindows(request) {
    return $Call.ByID(1858283168, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ListenAddr() {
    return $Call.ByID(305533821);
}

/**
 * MarkAttachPopupClosePrepared records that the popup began its close.
 * @param {string} sessionID
 * @param {string} authorization
 * @returns {$CancellablePromise<terminaluse$0.ActionResult>}
 */
export function MarkAttachPopupClosePrepared(sessionID, authorization) {
    return $Call.ByID(1036612006, sessionID, authorization).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PluginSessionClosed ends a plugin-protocol session from the plugin side
 * with ordinary exit tracking.
 * @param {string} sessionID
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function PluginSessionClosed(sessionID, reason) {
    return $Call.ByID(4116929858, sessionID, reason);
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function ProbeSystemCapabilities(sessionID) {
    return $Call.ByID(2006892894, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * PtyGetChildProcesses lists the direct children of a local session's shell
 * for the busy-close confirmation.
 * @param {string} sessionID
 * @returns {$CancellablePromise<terminaluse$0.ChildProcessInfo[]>}
 */
export function PtyGetChildProcesses(sessionID) {
    return $Call.ByID(1101459439, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * PublishPluginOutput forwards plugin connection output into the session's
 * ordinary data plane (flow control, observers, route publishing).
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<boolean>}
 */
export function PublishPluginOutput(sessionID, data) {
    return $Call.ByID(416369566, sessionID, data);
}

/**
 * ReadRemoteHistory tails the remote shell's history file(s) over one exec
 * channel on the existing transport.
 * @param {string} sessionID
 * @param {number} limit
 * @returns {$CancellablePromise<terminaluse$0.RemoteHistoryResult>}
 */
export function ReadRemoteHistory(sessionID, limit) {
    return $Call.ByID(3945696133, sessionID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * RebindSessionOutput rotates the data-plane route for the attach popup.
 * @param {string} sessionID
 * @param {string} authorization
 * @returns {$CancellablePromise<terminaluse$0.RebindResult>}
 */
export function RebindSessionOutput(sessionID, authorization) {
    return $Call.ByID(3384579440, sessionID, authorization).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {string} destinationDir
 * @returns {$CancellablePromise<ymodem$0.ReceiveResult[]>}
 */
export function ReceiveSerialYmodem(sessionID, destinationDir) {
    return $Call.ByID(3045917549, sessionID, destinationDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {string} destinationDir
 * @returns {$CancellablePromise<void>}
 */
export function ReceiveZmodem(sessionID, destinationDir) {
    return $Call.ByID(3664406058, sessionID, destinationDir);
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<dataplane$0.RouteBootstrap>}
 */
export function Reconnect(sessionID) {
    return $Call.ByID(2144418350, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RegisterPluginSession hosts a plugin-protocol connection as a first class
 * terminal session (the PluginConnectionSessionSink seam consumed by
 * PluginService.SetPluginSessionSink; see internal/app/terminaluse/
 * plugin_session.go).
 * @param {string} sessionID
 * @param {string} label
 * @param {terminaluse$0.PluginSessionHooks} hooks
 * @returns {$CancellablePromise<void>}
 */
export function RegisterPluginSession(sessionID, label, hooks) {
    return $Call.ByID(3374534853, sessionID, label, hooks);
}

/**
 * ReleaseSessionFlowPauseLease drops one lease and flushes buffered output.
 * @param {string} sessionID
 * @param {string} leaseID
 * @param {terminaluse$0.FlowPauseReleaseOptions | null} options
 * @returns {$CancellablePromise<terminaluse$0.ActionResult>}
 */
export function ReleaseSessionFlowPauseLease(sessionID, leaseID, options) {
    return $Call.ByID(3697294414, sessionID, leaseID, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RequestSessionSnapshot asks the home renderer to serialize its scrollback.
 * @param {string} sessionID
 * @param {string} authorization
 * @returns {$CancellablePromise<terminaluse$0.SnapshotResult>}
 */
export function RequestSessionSnapshot(sessionID, authorization) {
    return $Call.ByID(2897540114, sessionID, authorization).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(sessionID, cols, rows) {
    return $Call.ByID(270758441, sessionID, cols, rows);
}

/**
 * RespondApplySnapshot completes a pending apply-snapshot push (home renderer).
 * @param {string} requestID
 * @param {boolean} accepted
 * @returns {$CancellablePromise<void>}
 */
export function RespondApplySnapshot(requestID, accepted) {
    return $Call.ByID(3392555066, requestID, accepted);
}

/**
 * RespondHostKeyVerification completes or rejects a pending changed host-key
 * confirmation. accept+addToKnownHosts rotates the pinned key; accept alone
 * allows exactly this connection.
 * @param {string} requestID
 * @param {boolean} accept
 * @param {boolean} addToKnownHosts
 * @returns {$CancellablePromise<void>}
 */
export function RespondHostKeyVerification(requestID, accept, addToKnownHosts) {
    return $Call.ByID(1637849568, requestID, accept, addToKnownHosts);
}

/**
 * @param {string} requestID
 * @param {string[]} responses
 * @param {boolean} cancelled
 * @returns {$CancellablePromise<void>}
 */
export function RespondKeyboardInteractive(requestID, responses, cancelled) {
    return $Call.ByID(547631165, requestID, responses, cancelled);
}

/**
 * RespondPassphrase completes or cancels a pending encrypted-key passphrase
 * prompt raised during SSH auth.
 * @param {string} requestID
 * @param {string} passphrase
 * @param {boolean} cancelled
 * @returns {$CancellablePromise<void>}
 */
export function RespondPassphrase(requestID, passphrase, cancelled) {
    return $Call.ByID(4197099922, requestID, passphrase, cancelled);
}

/**
 * RespondSessionSnapshot completes a pending snapshot request (home renderer).
 * @param {string} requestID
 * @param {string} snapshot
 * @param {terminaluse$0.KittyKeyboardModeState | null} kittyState
 * @param {boolean | null} kittyEnabled
 * @param {boolean | null} passwordPromptActive
 * @param {string | null} cwd
 * @param {string | null} title
 * @returns {$CancellablePromise<void>}
 */
export function RespondSessionSnapshot(requestID, snapshot, kittyState, kittyEnabled, passwordPromptActive, cwd, title) {
    return $Call.ByID(1130199870, requestID, snapshot, kittyState, kittyEnabled, passwordPromptActive, cwd, title);
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.HelperSessionState>}
 */
export function RestartHelper(sessionID) {
    return $Call.ByID(2694891548, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * RestoreSessionOutput rotates the route back to the home renderer.
 * @param {string} sessionID
 * @param {string} authorization
 * @returns {$CancellablePromise<terminaluse$0.ActionResult>}
 */
export function RestoreSessionOutput(sessionID, authorization) {
    return $Call.ByID(3696481350, sessionID, authorization).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RunnerFor exposes the transport-specific command runner for the agent
 * job queue (W13). Not a Wails method.
 * @param {string} sessionID
 * @returns {$CancellablePromise<terminaluse$0.CommandRunner>}
 */
export function RunnerFor(sessionID) {
    return $Call.ByID(3449065190, sessionID);
}

/**
 * @param {string} sessionID
 * @param {string} filePath
 * @returns {$CancellablePromise<ymodem$0.SendResult>}
 */
export function SendSerialYmodem(sessionID, filePath) {
    return $Call.ByID(4074171664, sessionID, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {string} filePath
 * @param {string} remoteName
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function SendZmodem(sessionID, filePath, remoteName, command) {
    return $Call.ByID(695933495, sessionID, filePath, remoteName, command);
}

/**
 * SetSessionEncoding pins the terminal input charset for one session. The
 * renderer decodes output with the same charset on the data plane; the Go
 * side encodes keystrokes before they reach the PTY/telnet/serial stream.
 * @param {string} sessionID
 * @param {string} encoding
 * @returns {$CancellablePromise<$models.TerminalEncodingResult>}
 */
export function SetSessionEncoding(sessionID, encoding) {
    return $Call.ByID(235362832, sessionID, encoding).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * SetSessionFlowPaused pauses/resumes output without a lease.
 * @param {string} sessionID
 * @param {boolean} paused
 * @returns {$CancellablePromise<void>}
 */
export function SetSessionFlowPaused(sessionID, paused) {
    return $Call.ByID(841481979, sessionID, paused);
}

/**
 * SetSessionFlowPausedAndWait pauses and waits for the queue to drain.
 * @param {string} sessionID
 * @param {boolean} paused
 * @returns {$CancellablePromise<terminaluse$0.ActionResult>}
 */
export function SetSessionFlowPausedAndWait(sessionID, paused) {
    return $Call.ByID(4135377229, sessionID, paused).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {string} command
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function SetupOsc7Tracking(sessionID, command) {
    return $Call.ByID(1680930791, sessionID, command).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {string} signal
 * @returns {$CancellablePromise<void>}
 */
export function Signal(sessionID, signal) {
    return $Call.ByID(4236247009, sessionID, signal);
}

/**
 * @param {$models.ProcessSignalOptions} options
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function SignalSystemProcess(options) {
    return $Call.ByID(512255837, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.MoshStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartEt(request) {
    return $Call.ByID(2928365382, request);
}

/**
 * @param {string} shell
 * @param {string} cwd
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<string>}
 */
export function StartLocal(shell, cwd, cols, rows) {
    return $Call.ByID(3430581078, shell, cwd, cols, rows);
}

/**
 * @param {$models.LocalStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartLocalWithOptions(request) {
    return $Call.ByID(4092120380, request);
}

/**
 * @param {$models.MoshStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartMosh(request) {
    return $Call.ByID(2465988376, request);
}

/**
 * @param {$models.SerialStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartSerial(request) {
    return $Call.ByID(2462094395, request);
}

/**
 * @param {$models.TelnetStartRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function StartTelnet(request) {
    return $Call.ByID(3093898707, request);
}

/**
 * @param {$models.SystemServiceActionRequest} request
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function SystemServiceAction(request) {
    return $Call.ByID(3026757165, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * TestProxy probes HTTP/SOCKS5/ProxyCommand reachability without opening a session.
 * @param {$models.ProxyProbeRequest} request
 * @returns {$CancellablePromise<$models.ProxyProbeResult>}
 */
export function TestProxy(request) {
    return $Call.ByID(3774340899, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @param {$models.TmuxActionRequest} request
 * @returns {$CancellablePromise<$models.MonitoringResult>}
 */
export function TmuxAction(request) {
    return $Call.ByID(2420520077, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * TransportFor exposes a live session's authenticated SSH client for the SFTP
 * subsystem seam; see terminaluse.Service.TransportFor.
 * @param {string} sessionID
 * @returns {$CancellablePromise<[ssh$0.Client | null, any]>}
 */
export function TransportFor(sessionID) {
    return $Call.ByID(1529495929, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType32($result[0]);
        return $result;
    }));
}

/**
 * @param {string} path
 * @param {string} kind
 * @returns {$CancellablePromise<$models.PathValidation>}
 */
export function ValidatePath(path, kind) {
    return $Call.ByID(1211764756, path, kind).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * WaitSessionFlowPauseLease waits for pre-pause output to drain.
 * @param {string} sessionID
 * @param {string} leaseID
 * @returns {$CancellablePromise<terminaluse$0.ActionResult>}
 */
export function WaitSessionFlowPauseLease(sessionID, leaseID) {
    return $Call.ByID(1602523668, sessionID, leaseID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<number>}
 */
export function Write(sessionID, data) {
    return $Call.ByID(371925220, sessionID, data);
}

// Private type creation functions
const $$createType0 = terminaluse$0.FlowPauseLease.createFrom;
const $$createType1 = terminaluse$0.ActionResult.createFrom;
const $$createType2 = dataplane$0.RouteBootstrap.createFrom;
const $$createType3 = $models.SSHAgentStatus.createFrom;
const $$createType4 = terminaluse$0.MonitoringResult.createFrom;
const $$createType5 = terminaluse$0.DiscoveredShell.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = terminaluse$0.ExecResult.createFrom;
const $$createType8 = $models.KeyPairResult.createFrom;
const $$createType9 = $models.DefaultSSHKey.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = terminaluse$0.TerminalExitStatus.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = terminaluse$0.HelperSessionState.createFrom;
const $$createType14 = terminaluse$0.SessionDistroResult.createFrom;
const $$createType15 = terminaluse$0.TerminalPwdResult.createFrom;
const $$createType16 = terminaluse$0.TerminalRemoteInfo.createFrom;
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
const $$createType18 = terminaluse$0.AutocompleteDirectoryResult.createFrom;
const $$createType19 = serialport$0.Info.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = terminaluse$0.ChildProcessInfo.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = terminaluse$0.RemoteHistoryResult.createFrom;
const $$createType24 = terminaluse$0.RebindResult.createFrom;
const $$createType25 = ymodem$0.ReceiveResult.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = terminaluse$0.SnapshotResult.createFrom;
const $$createType28 = ymodem$0.SendResult.createFrom;
const $$createType29 = $models.TerminalEncodingResult.createFrom;
const $$createType30 = terminaluse$0.ProxyProbeResult.createFrom;
const $$createType31 = ssh$0.Client.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = terminaluse$0.PathValidation.createFrom;
