// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService is the Wails-facing in-app update facade. It owns no update
 * logic: state, downloads, verification and install live in
 * internal/app/updateuse. Event names and payload shapes mirror the
 * electron-updater bridge contract consumed by useUpdateCheck
 * (types/global/lemonssh-bridge-app.d.ts).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updateuse$0 from "../../internal/app/updateuse/models.js";

/**
 * AutoCheck runs the throttled startup check. The shell schedules it after
 * the first window's runtime is ready so update events reach renderers.
 * @returns {$CancellablePromise<void>}
 */
export function AutoCheck() {
    return $Call.ByID(1572297865);
}

/**
 * CheckForUpdate queries GitHub Releases for a newer version. When
 * auto-update is on, the download starts in the background and progress
 * arrives through the update:* events.
 * @returns {$CancellablePromise<updateuse$0.CheckResult>}
 */
export function CheckForUpdate() {
    return $Call.ByID(654227894).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DownloadUpdate downloads the pending artifact; progress streams through
 * update:download-progress. Resolves when the download completes.
 * @returns {$CancellablePromise<updateuse$0.DownloadResult>}
 */
export function DownloadUpdate() {
    return $Call.ByID(943505489).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAutoUpdate reports the persisted auto-download toggle.
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetAutoUpdate() {
    return $Call.ByID(3051248522).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetUpdateStatus hydrates renderer state (late-opening windows, retries).
 * @returns {$CancellablePromise<updateuse$0.StatusSnapshot>}
 */
export function GetUpdateStatus() {
    return $Call.ByID(166669511).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * InstallUpdate swaps the running executable with the downloaded artifact,
 * schedules a relaunch and quits the app.
 * @returns {$CancellablePromise<void>}
 */
export function InstallUpdate() {
    return $Call.ByID(2153346210);
}

/**
 * SetAutoUpdate persists the auto-download toggle.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function SetAutoUpdate(enabled) {
    return $Call.ByID(1370280902, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = updateuse$0.CheckResult.createFrom;
const $$createType1 = updateuse$0.DownloadResult.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = updateuse$0.StatusSnapshot.createFrom;
