// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} prompt
 * @param {string[]} selectedSkillSlugs
 * @returns {$CancellablePromise<$models.UserSkillsContextResult>}
 */
export function BuildContext(prompt, selectedSkillSlugs) {
    return $Call.ByID(2597642695, prompt, selectedSkillSlugs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.UserSkillsStatusResult>}
 */
export function GetStatus() {
    return $Call.ByID(2868785938).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.UserSkillsStatusResult>}
 */
export function OpenFolder() {
    return $Call.ByID(895917984).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.UserSkillsContextResult.createFrom;
const $$createType1 = $models.UserSkillsStatusResult.createFrom;
