// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowLifecycleService owns main-window close semantics for the Wails shell:
 * the quit guard (unsaved editors / running transfers), close-to-tray, window
 * opacity, and the show/hide/focus events the renderer's input-focus recovery
 * subscribes to. It is registered as a Wails service; SetCloseToTray,
 * IsCloseToTray, SetWindowOpacity, ReportDirtyEditorsResult and RequestClose
 * are renderer-callable bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * IsCloseToTray reports the shell's current close-to-tray setting.
 * @returns {$CancellablePromise<$models.windowFlagResult>}
 */
export function IsCloseToTray() {
    return $Call.ByID(1075704210).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ReportDirtyEditorsResult resolves the pending quit-guard query. The
 * renderer listens for window:check-dirty-editors and reports back through
 * this binding (LemonSSHBridge.reportDirtyEditorsResult).
 * @param {boolean} hasDirty
 * @returns {$CancellablePromise<void>}
 */
export function ReportDirtyEditorsResult(hasDirty) {
    return $Call.ByID(275579836, hasDirty);
}

/**
 * RequestClose resolves a renderer-initiated close for the calling window.
 * The renderer passes its own Wails window name: "main" (or empty) runs the
 * quit guard — close-to-tray hides, otherwise the dirty-editor round trip
 * decides between staying open and quitting. Any other name closes that
 * window directly; the window's own WindowClosing hooks keep their policy
 * (settings hides to stay warm, popups honour the owner close-attempt gate),
 * so this method never bypasses an existing close contract.
 * @param {string} window
 * @returns {$CancellablePromise<$models.windowCloseResult>}
 */
export function RequestClose(window) {
    return $Call.ByID(479464974, window).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetCloseToTray syncs the renderer's close-to-tray setting into the shell.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.windowFlagResult>}
 */
export function SetCloseToTray(enabled) {
    return $Call.ByID(765060208, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetWindowOpacity applies whole-window transparency to the main window.
 * Returns false when the platform cannot honour it (unsupported platform or
 * no main window); the renderer surfaces that as a skipped apply.
 * @param {number} opacity
 * @returns {$CancellablePromise<boolean>}
 */
export function SetWindowOpacity(opacity) {
    return $Call.ByID(1254155504, opacity);
}

// Private type creation functions
const $$createType0 = $models.windowFlagResult.createFrom;
const $$createType1 = $models.windowCloseResult.createFrom;
