// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";

/**
 * Contribution wraps a declaration with the declaring plugin's identity.
 */
export class Contribution {
    /**
     * Creates a new Contribution instance.
     * @param {Partial<Contribution>} [$$source = {}] - The source object to create the Contribution.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("pluginVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginVersion"] = "";
        }
        if (!("pluginDisplayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginDisplayName"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {Declaration}
             */
            this["provider"] = (new Declaration());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Contribution instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Contribution}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("provider" in $$parsedSource) {
            $$parsedSource["provider"] = $$createField3_0($$parsedSource["provider"]);
        }
        return new Contribution(/** @type {Partial<Contribution>} */($$parsedSource));
    }
}

/**
 * Declaration is one validated provider contribution (contract
 * ProviderContribution, localized labels resolved to plain strings).
 */
export class Declaration {
    /**
     * Creates a new Declaration instance.
     * @param {Partial<Declaration>} [$$source = {}] - The source object to create the Declaration.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["capabilities"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["configurationSchema"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Declaration instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Declaration}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField4_0($$parsedSource["capabilities"]);
        }
        return new Declaration(/** @type {Partial<Declaration>} */($$parsedSource));
    }
}

/**
 * ProviderError is the failed-result payload (numeric wire code, contract
 * RpcErrorObject shape).
 */
export class ProviderError {
    /**
     * Creates a new ProviderError instance.
     * @param {Partial<ProviderError>} [$$source = {}] - The source object to create the ProviderError.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["code"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderError instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderError}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderError(/** @type {Partial<ProviderError>} */($$parsedSource));
    }
}

/**
 * SessionDelivery reports one plugin's session-event delivery outcome.
 */
export class SessionDelivery {
    /**
     * Creates a new SessionDelivery instance.
     * @param {Partial<SessionDelivery>} [$$source = {}] - The source object to create the SessionDelivery.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("delivered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["delivered"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionDelivery instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionDelivery}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionDelivery(/** @type {Partial<SessionDelivery>} */($$parsedSource));
    }
}

/**
 * SessionEvent is one terminal session lifecycle notification.
 */
export class SessionEvent {
    /**
     * Creates a new SessionEvent instance.
     * @param {Partial<SessionEvent>} [$$source = {}] - The source object to create the SessionEvent.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {TerminalSessionSnapshot}
             */
            this["session"] = (new TerminalSessionSnapshot());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["exitCode"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionEvent}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField1_0($$parsedSource["session"]);
        }
        return new SessionEvent(/** @type {Partial<SessionEvent>} */($$parsedSource));
    }
}

/**
 * TerminalRequest is one provider invocation fan-out (renderer
 * LemonsshTerminalProviderRequest).
 */
export class TerminalRequest {
    /**
     * Creates a new TerminalRequest instance.
     * @param {Partial<TerminalRequest>} [$$source = {}] - The source object to create the TerminalRequest.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("operation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operation"] = "";
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {TerminalSessionSnapshot}
             */
            this["session"] = (new TerminalSessionSnapshot());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["payload"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["locale"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["preferredProviderIds"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["deadlineMs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField3_0($$parsedSource["session"]);
        }
        if ("preferredProviderIds" in $$parsedSource) {
            $$parsedSource["preferredProviderIds"] = $$createField6_0($$parsedSource["preferredProviderIds"]);
        }
        return new TerminalRequest(/** @type {Partial<TerminalRequest>} */($$parsedSource));
    }
}

/**
 * TerminalResult is one provider's answer (renderer
 * LemonsshTerminalProviderResult).
 */
export class TerminalResult {
    /**
     * Creates a new TerminalResult instance.
     * @param {Partial<TerminalResult>} [$$source = {}] - The source object to create the TerminalResult.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("pluginVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginVersion"] = "";
        }
        if (!("providerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["providerId"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["result"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ProviderError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalResult}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField7_0($$parsedSource["error"]);
        }
        return new TerminalResult(/** @type {Partial<TerminalResult>} */($$parsedSource));
    }
}

/**
 * TerminalSessionSnapshot is the immutable session metadata providers receive
 * (renderer LemonsshTerminalSessionSnapshot).
 */
export class TerminalSessionSnapshot {
    /**
     * Creates a new TerminalSessionSnapshot instance.
     * @param {Partial<TerminalSessionSnapshot>} [$$source = {}] - The source object to create the TerminalSessionSnapshot.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workspaceId"] = undefined;
        }
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["shellType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cols"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["rows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["alternateScreen"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalSessionSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalSessionSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalSessionSnapshot(/** @type {Partial<TerminalSessionSnapshot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Declaration.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = TerminalSessionSnapshot.createFrom;
const $$createType3 = ProviderError.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
