// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AgentEventEnvelope is one turn event. Sequence is a decimal string so the
 * JavaScript side never loses precision on uint64 counters.
 */
export class AgentEventEnvelope {
    /**
     * Creates a new AgentEventEnvelope instance.
     * @param {Partial<AgentEventEnvelope>} [$$source = {}] - The source object to create the AgentEventEnvelope.
     */
    constructor($$source = {}) {
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("instanceId" in $$source)) {
            /**
             * @member
             * @type {InstanceID}
             */
            this["instanceId"] = "";
        }
        if (!("chatSessionId" in $$source)) {
            /**
             * @member
             * @type {ChatSessionID}
             */
            this["chatSessionId"] = "";
        }
        if (!("turnId" in $$source)) {
            /**
             * @member
             * @type {TurnID}
             */
            this["turnId"] = "";
        }
        if (!("sequence" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sequence"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backend"] = "";
        }
        if (!("timestampMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestampMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["messageId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["modelCallId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["toolCallId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["payload"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentEventEnvelope instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentEventEnvelope}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField11_0($$parsedSource["payload"]);
        }
        return new AgentEventEnvelope(/** @type {Partial<AgentEventEnvelope>} */($$parsedSource));
    }
}

/**
 * AgentID identifies one agent kind or adapter.
 * @typedef {string} AgentID
 */

/**
 * ChatSessionID identifies one AI chat session.
 * @typedef {string} ChatSessionID
 */

/**
 * EventPage is one ReadEvents response. Snapshot arrives only when the host
 * evicted the ring section the cursor points into.
 */
export class EventPage {
    /**
     * Creates a new EventPage instance.
     * @param {Partial<EventPage>} [$$source = {}] - The source object to create the EventPage.
     */
    constructor($$source = {}) {
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {AgentEventEnvelope[]}
             */
            this["events"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["nextCursor"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["hasMore"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["cursorExpired"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TurnSnapshot | null | undefined}
             */
            this["snapshot"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventPage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventPage}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField0_0($$parsedSource["events"]);
        }
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField4_0($$parsedSource["snapshot"]);
        }
        return new EventPage(/** @type {Partial<EventPage>} */($$parsedSource));
    }
}

/**
 * InstanceID identifies one running application instance.
 * @typedef {string} InstanceID
 */

/**
 * PrepareTurnRequest asks the host to reserve one turn slot. The host
 * validates scope and revisions and never contacts a provider.
 */
export class PrepareTurnRequest {
    /**
     * Creates a new PrepareTurnRequest instance.
     * @param {Partial<PrepareTurnRequest>} [$$source = {}] - The source object to create the PrepareTurnRequest.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {RequestID}
             */
            this["requestId"] = "";
        }
        if (!("chatSessionId" in $$source)) {
            /**
             * @member
             * @type {ChatSessionID}
             */
            this["chatSessionId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["expectedChatRevision"] = undefined;
        }
        if (!("agentId" in $$source)) {
            /**
             * @member
             * @type {AgentID}
             */
            this["agentId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["providerConfigId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["modelId"] = undefined;
        }
        if (!("input" in $$source)) {
            /**
             * @member
             * @type {TurnInput}
             */
            this["input"] = (new TurnInput());
        }
        if (!("requestedScope" in $$source)) {
            /**
             * @member
             * @type {TurnScope}
             */
            this["requestedScope"] = (new TurnScope());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrepareTurnRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PrepareTurnRequest}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField6_0($$parsedSource["input"]);
        }
        if ("requestedScope" in $$parsedSource) {
            $$parsedSource["requestedScope"] = $$createField7_0($$parsedSource["requestedScope"]);
        }
        return new PrepareTurnRequest(/** @type {Partial<PrepareTurnRequest>} */($$parsedSource));
    }
}

/**
 * PreparedTurn is the host reservation for one turn. It carries no secret
 * material and expires when the lease lapses.
 */
export class PreparedTurn {
    /**
     * Creates a new PreparedTurn instance.
     * @param {Partial<PreparedTurn>} [$$source = {}] - The source object to create the PreparedTurn.
     */
    constructor($$source = {}) {
        if (!("turnId" in $$source)) {
            /**
             * @member
             * @type {TurnID}
             */
            this["turnId"] = "";
        }
        if (!("leaseExpiresAtMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["leaseExpiresAtMs"] = 0;
        }
        if (!("cursor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cursor"] = "";
        }
        if (!("snapshotRevision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snapshotRevision"] = "";
        }
        if (!("effectiveScope" in $$source)) {
            /**
             * @member
             * @type {TurnScope}
             */
            this["effectiveScope"] = (new TurnScope());
        }
        if (!("effectiveConfigRevision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["effectiveConfigRevision"] = "";
        }
        if (!("policyRevision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["policyRevision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreparedTurn instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreparedTurn}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("effectiveScope" in $$parsedSource) {
            $$parsedSource["effectiveScope"] = $$createField4_0($$parsedSource["effectiveScope"]);
        }
        return new PreparedTurn(/** @type {Partial<PreparedTurn>} */($$parsedSource));
    }
}

/**
 * RequestID correlates one request/response pair.
 * @typedef {string} RequestID
 */

/**
 * TurnCommand starts, stops or steers a turn. Start requires the prepare
 * lease; Stop carries a reason; Steer carries input plus the expected turn
 * revision so concurrent writers fail closed.
 */
export class TurnCommand {
    /**
     * Creates a new TurnCommand instance.
     * @param {Partial<TurnCommand>} [$$source = {}] - The source object to create the TurnCommand.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {RequestID}
             */
            this["requestId"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {TurnCommandKind}
             */
            this["kind"] = TurnCommandKind.$zero;
        }
        if (!("turnId" in $$source)) {
            /**
             * @member
             * @type {TurnID}
             */
            this["turnId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TurnInput | null | undefined}
             */
            this["input"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["expectedTurnRevision"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TurnCommand instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TurnCommand}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField4_0($$parsedSource["input"]);
        }
        return new TurnCommand(/** @type {Partial<TurnCommand>} */($$parsedSource));
    }
}

/**
 * TurnCommandKind selects the lifecycle command for a prepared or running turn.
 * @readonly
 * @enum {string}
 */
export const TurnCommandKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TurnCommandStart: "start",
    TurnCommandStop: "stop",
    TurnCommandSteer: "steer",
};

/**
 * TurnID identifies one prepared or running AI turn.
 * @typedef {string} TurnID
 */

/**
 * TurnInput is the user-supplied text plus attachment references.
 */
export class TurnInput {
    /**
     * Creates a new TurnInput instance.
     * @param {Partial<TurnInput>} [$$source = {}] - The source object to create the TurnInput.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["attachmentIds"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TurnInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TurnInput}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachmentIds" in $$parsedSource) {
            $$parsedSource["attachmentIds"] = $$createField1_0($$parsedSource["attachmentIds"]);
        }
        return new TurnInput(/** @type {Partial<TurnInput>} */($$parsedSource));
    }
}

/**
 * TurnScope is the host-narrowed set of operations a turn may use. The
 * request carries a wish; the host records what it actually granted.
 */
export class TurnScope {
    /**
     * Creates a new TurnScope instance.
     * @param {Partial<TurnScope>} [$$source = {}] - The source object to create the TurnScope.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["terminalRead"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["terminalWrite"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["exec"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["sftpRead"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["sftpWrite"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TurnScope instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TurnScope}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TurnScope(/** @type {Partial<TurnScope>} */($$parsedSource));
    }
}

/**
 * TurnSnapshot is the authoritative projection replacing stale cursors. It
 * carries no opaque provider continuation.
 */
export class TurnSnapshot {
    /**
     * Creates a new TurnSnapshot instance.
     * @param {Partial<TurnSnapshot>} [$$source = {}] - The source object to create the TurnSnapshot.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["revision"] = "";
        }
        if (!("throughSequence" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["throughSequence"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["terminalReason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["usageComplete"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["pendingInteractions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["activeJobs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TurnSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TurnSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TurnSnapshot(/** @type {Partial<TurnSnapshot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AgentEventEnvelope.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = TurnSnapshot.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = TurnInput.createFrom;
const $$createType5 = TurnScope.createFrom;
const $$createType6 = $Create.Nullable($$createType4);
const $$createType7 = $Create.Array($Create.Any);
