// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";

export class ContributionKeybinding {
    /**
     * Creates a new ContributionKeybinding instance.
     * @param {Partial<ContributionKeybinding>} [$$source = {}] - The source object to create the ContributionKeybinding.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mac"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["linux"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["windows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["args"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContributionKeybinding instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContributionKeybinding}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContributionKeybinding(/** @type {Partial<ContributionKeybinding>} */($$parsedSource));
    }
}

export class ContributionMenu {
    /**
     * Creates a new ContributionMenu instance.
     * @param {Partial<ContributionMenu>} [$$source = {}] - The source object to create the ContributionMenu.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["alt"] = undefined;
        }
        if (!("location" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["location"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["group"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["order"] = undefined;
        }
        if (!("visible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["visible"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContributionMenu instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContributionMenu}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContributionMenu(/** @type {Partial<ContributionMenu>} */($$parsedSource));
    }
}

/**
 * ContributionView/Menu/Keybinding are the host-facing contribution records
 * derived from a validated Schema; CollectContributions applies the nil-means
 * defaults so consumers (bridge, Wails renderer) never re-derive them.
 */
export class ContributionView {
    /**
     * Creates a new ContributionView instance.
     * @param {Partial<ContributionView>} [$$source = {}] - The source object to create the ContributionView.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("location" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["location"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["columns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["bindings"] = undefined;
        }
        if (!("visible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["visible"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContributionView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContributionView}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField5_0($$parsedSource["columns"]);
        }
        if ("bindings" in $$parsedSource) {
            $$parsedSource["bindings"] = $$createField6_0($$parsedSource["bindings"]);
        }
        return new ContributionView(/** @type {Partial<ContributionView>} */($$parsedSource));
    }
}

/**
 * Contributions is the aggregate declarative UI contribution set of one
 * plugin (or of every enabled plugin when the host aggregates).
 */
export class Contributions {
    /**
     * Creates a new Contributions instance.
     * @param {Partial<Contributions>} [$$source = {}] - The source object to create the Contributions.
     */
    constructor($$source = {}) {
        if (!("views" in $$source)) {
            /**
             * @member
             * @type {ContributionView[]}
             */
            this["views"] = [];
        }
        if (!("menus" in $$source)) {
            /**
             * @member
             * @type {ContributionMenu[]}
             */
            this["menus"] = [];
        }
        if (!("keybindings" in $$source)) {
            /**
             * @member
             * @type {ContributionKeybinding[]}
             */
            this["keybindings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Contributions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Contributions}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("views" in $$parsedSource) {
            $$parsedSource["views"] = $$createField0_0($$parsedSource["views"]);
        }
        if ("menus" in $$parsedSource) {
            $$parsedSource["menus"] = $$createField1_0($$parsedSource["menus"]);
        }
        if ("keybindings" in $$parsedSource) {
            $$parsedSource["keybindings"] = $$createField2_0($$parsedSource["keybindings"]);
        }
        return new Contributions(/** @type {Partial<Contributions>} */($$parsedSource));
    }
}

/**
 * KeybindingDef binds one plugin command to an accelerator. Platform-specific
 * overrides are optional; Enabled defaults to true when nil.
 */
export class KeybindingDef {
    /**
     * Creates a new KeybindingDef instance.
     * @param {Partial<KeybindingDef>} [$$source = {}] - The source object to create the KeybindingDef.
     */
    constructor($$source = {}) {
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mac"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["linux"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["windows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * pre-validated JSON payload for the command
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["args"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["enabled"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeybindingDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeybindingDef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeybindingDef(/** @type {Partial<KeybindingDef>} */($$parsedSource));
    }
}

/**
 * MenuDef declares one menu entry that surfaces a plugin command. The
 * referenced command must exist in the manifest's contributions (validated by
 * the manifest package, which sees both blocks).
 */
export class MenuDef {
    /**
     * Creates a new MenuDef instance.
     * @param {Partial<MenuDef>} [$$source = {}] - The source object to create the MenuDef.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * alternate command id
             * @member
             * @type {string | undefined}
             */
            this["alt"] = undefined;
        }
        if (!("location" in $$source)) {
            /**
             * commandPalette | application | host/context | terminal/context | terminal/toolbar | statusBar
             * @member
             * @type {string}
             */
            this["location"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * label override; falls back to the command id
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * sort group
             * @member
             * @type {string | undefined}
             */
            this["group"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * sort order inside the group
             * @member
             * @type {number | undefined}
             */
            this["order"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * nil means visible
             * @member
             * @type {boolean | null | undefined}
             */
            this["visible"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MenuDef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MenuDef(/** @type {Partial<MenuDef>} */($$parsedSource));
    }
}

/**
 * Schema is the root declarative UI definition for one plugin.
 */
export class Schema {
    /**
     * Creates a new Schema instance.
     * @param {Partial<Schema>} [$$source = {}] - The source object to create the Schema.
     */
    constructor($$source = {}) {
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {SettingField[]}
             */
            this["settings"] = [];
        }
        if (!("views" in $$source)) {
            /**
             * @member
             * @type {ViewDef[]}
             */
            this["views"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {MenuDef[] | undefined}
             */
            this["menus"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {KeybindingDef[] | undefined}
             */
            this["keybindings"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Schema instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Schema}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField0_0($$parsedSource["settings"]);
        }
        if ("views" in $$parsedSource) {
            $$parsedSource["views"] = $$createField1_0($$parsedSource["views"]);
        }
        if ("menus" in $$parsedSource) {
            $$parsedSource["menus"] = $$createField2_0($$parsedSource["menus"]);
        }
        if ("keybindings" in $$parsedSource) {
            $$parsedSource["keybindings"] = $$createField3_0($$parsedSource["keybindings"]);
        }
        return new Schema(/** @type {Partial<Schema>} */($$parsedSource));
    }
}

/**
 * SettingField is one form field.
 */
export class SettingField {
    /**
     * Creates a new SettingField instance.
     * @param {Partial<SettingField>} [$$source = {}] - The source object to create the SettingField.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "text" | "number" | "boolean" | "select" | "password"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["default"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * for select
             * @member
             * @type {string[] | undefined}
             */
            this["options"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["required"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingField}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new SettingField(/** @type {Partial<SettingField>} */($$parsedSource));
    }
}

/**
 * ViewDef is one declarative view. Location is restricted to
 * ViewLocationSettings for now; Visible defaults to true when nil so existing
 * manifests keep rendering their views.
 */
export class ViewDef {
    /**
     * Creates a new ViewDef instance.
     * @param {Partial<ViewDef>} [$$source = {}] - The source object to create the ViewDef.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "list" | "card"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * only "settings" is supported today
             * @member
             * @type {string | undefined}
             */
            this["location"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * for list
             * @member
             * @type {string[] | undefined}
             */
            this["columns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * data bindings
             * @member
             * @type {string[] | undefined}
             */
            this["bindings"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * nil means visible
             * @member
             * @type {boolean | null | undefined}
             */
            this["visible"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ViewDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ViewDef}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField4_0($$parsedSource["columns"]);
        }
        if ("bindings" in $$parsedSource) {
            $$parsedSource["bindings"] = $$createField5_0($$parsedSource["bindings"]);
        }
        return new ViewDef(/** @type {Partial<ViewDef>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ContributionView.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ContributionMenu.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ContributionKeybinding.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = SettingField.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ViewDef.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = MenuDef.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = KeybindingDef.createFrom;
const $$createType14 = $Create.Array($$createType13);
