// Package script owns terminal script recording and later execution.
// Recording is independent of the Node worker used by the Electron runtime.
package script

import (
	"encoding/json"
	"fmt"
	"strings"
	"sync"
	"time"
)

const (
	MaxRecordingSteps = 10_000
	MaxRecordingBytes = 2 * 1024 * 1024
	LimitError        = "Recording stopped because it reached the safety limit"
	header            = "// Auto-generated by Netcatty Script Recorder"
)

// Step is one recorded script action.
type Step struct {
	Type      string `json:"type"`
	Value     any    `json:"value,omitempty"`
	TimeoutMs int    `json:"timeoutMs,omitempty"`
	Sensitive bool   `json:"sensitive,omitempty"`
}

type recording struct {
	sessionID     string
	startedAt     time.Time
	lastTimestamp time.Time
	steps         []Step
	totalBytes    int
}

// Recorder owns in-memory recordings keyed by terminal session ID.
type Recorder struct {
	mu         sync.Mutex
	recordings map[string]*recording
	now        func() time.Time
}

func NewRecorder() *Recorder {
	return &Recorder{
		recordings: make(map[string]*recording),
		now:        time.Now,
	}
}

func (r *Recorder) Start(sessionID string) error {
	sessionID = strings.TrimSpace(sessionID)
	if sessionID == "" {
		return fmt.Errorf("sessionId required")
	}
	now := r.now()
	r.mu.Lock()
	defer r.mu.Unlock()
	r.recordings[sessionID] = &recording{
		sessionID:     sessionID,
		startedAt:     now,
		lastTimestamp: now,
	}
	return nil
}

type AppendResult struct {
	OK      bool   `json:"ok"`
	Stopped bool   `json:"stopped,omitempty"`
	Reason  string `json:"reason,omitempty"`
	Error   string `json:"error,omitempty"`
	Steps   []Step `json:"steps,omitempty"`
	Code    string `json:"code,omitempty"`
}

func (r *Recorder) Append(sessionID string, step Step) AppendResult {
	sessionID = strings.TrimSpace(sessionID)
	r.mu.Lock()
	defer r.mu.Unlock()
	rec := r.recordings[sessionID]
	if rec == nil {
		return AppendResult{Error: "Recording not started"}
	}
	if strings.TrimSpace(step.Type) == "" {
		return AppendResult{Error: "Recording step is required"}
	}
	now := r.now()
	gap := now.Sub(rec.lastTimestamp)
	additions := make([]Step, 0, 2)
	if gap > time.Second && step.Type == "send" {
		additions = append(additions, Step{Type: "sleep", Value: int(gap / time.Millisecond)})
	}
	additions = append(additions, step)
	additionBytes := 0
	for _, addition := range additions {
		encoded, err := json.Marshal(addition)
		if err != nil {
			return AppendResult{Error: "Invalid recording step"}
		}
		additionBytes += len(encoded)
	}
	nextCount := len(rec.steps) + len(additions)
	nextBytes := rec.totalBytes + additionBytes
	exceeds := nextCount > MaxRecordingSteps || nextBytes > MaxRecordingBytes
	if !exceeds {
		rec.steps = append(rec.steps, additions...)
		rec.totalBytes = nextBytes
		rec.lastTimestamp = now
	}
	if exceeds || len(rec.steps) >= MaxRecordingSteps || rec.totalBytes >= MaxRecordingBytes {
		steps := append([]Step(nil), rec.steps...)
		delete(r.recordings, sessionID)
		code := ""
		if len(steps) > 0 {
			code = StepsToJavaScript(steps, rec.startedAt.UTC().Format(time.RFC3339))
		}
		return AppendResult{
			Stopped: true,
			Reason:  "limit",
			Error:   LimitError,
			Steps:   steps,
			Code:    code,
		}
	}
	return AppendResult{OK: true}
}

type StopResult struct {
	Steps []Step `json:"steps"`
	Code  string `json:"code"`
}

func (r *Recorder) Stop(sessionID string) StopResult {
	r.mu.Lock()
	rec := r.recordings[sessionID]
	delete(r.recordings, sessionID)
	r.mu.Unlock()
	if rec == nil {
		return StopResult{Steps: []Step{}, Code: ""}
	}
	return StopResult{
		Steps: rec.steps,
		Code:  StepsToJavaScript(rec.steps, rec.startedAt.UTC().Format(time.RFC3339)),
	}
}

func (r *Recorder) Release(sessionID string) {
	r.mu.Lock()
	delete(r.recordings, sessionID)
	r.mu.Unlock()
}

func StepsToJavaScript(steps []Step, recordedAt string) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteByte('\n')
	if recordedAt != "" {
		b.WriteString("// Recorded on ")
		b.WriteString(recordedAt)
		b.WriteByte('\n')
	}
	b.WriteString("\nasync function main() {\n")
	for index, step := range steps {
		switch step.Type {
		case "send":
			if step.Sensitive {
				fmt.Fprintf(&b, "  const sensitiveValue%d = await nct.dialog.prompt(\"Enter sensitive value\", \"\", { sensitive: true });\n", index)
				fmt.Fprintf(&b, "  await nct.screen.sendLine(sensitiveValue%d, { sensitive: true });\n", index)
				continue
			}
			fmt.Fprintf(&b, "  await nct.screen.sendLine(%s);\n", jsString(step.Value))
		case "waitFor":
			timeout := step.TimeoutMs
			if timeout == 0 {
				timeout = 5000
			}
			fmt.Fprintf(&b, "  await nct.screen.waitForText(%s, %d);\n", jsString(step.Value), timeout)
		case "waitForPrompt":
			timeout := step.TimeoutMs
			if timeout == 0 {
				timeout = 30000
			}
			fmt.Fprintf(&b, "  await nct.screen.waitForPrompt(%d);\n", timeout)
		case "sleep":
			fmt.Fprintf(&b, "  await nct.session.sleep(%d);\n", intValue(step.Value, 1000))
		}
	}
	b.WriteString("}\n\nawait main();")
	return b.String()
}

func jsString(value any) string {
	encoded, err := json.Marshal(fmt.Sprint(value))
	if err != nil {
		return `""`
	}
	return string(encoded)
}

func intValue(value any, fallback int) int {
	switch n := value.(type) {
	case int:
		if n == 0 {
			return fallback
		}
		return n
	case int64:
		if n == 0 {
			return fallback
		}
		return int(n)
	case float64:
		if n == 0 {
			return fallback
		}
		return int(n)
	case json.Number:
		parsed, err := n.Int64()
		if err != nil || parsed == 0 {
			return fallback
		}
		return int(parsed)
	default:
		return fallback
	}
}
