package script

import (
	"strings"
	"testing"
	"time"
)

func TestParseRecordedScriptSleepSendAndPrompt(t *testing.T) {
	ops, err := ParseRecordedScript(`// Auto-generated by Netcatty Script Recorder
// Recorded on 2026-09-15T14:21:12Z

async function main() {
  await nct.session.sleep(3955);
  await nct.screen.sendLine("ls");
  await nct.screen.waitForPrompt(30000);
  await nct.session.sleep(3917);
  await nct.screen.sendLine("cd /data/");
  await nct.screen.waitForPrompt(30000);
}

await main();`)
	if err != nil {
		t.Fatal(err)
	}
	if len(ops) != 6 {
		t.Fatalf("ops=%d", len(ops))
	}
	if ops[0].Kind != "sleep" || ops[0].Timeout != 3955*time.Millisecond {
		t.Fatalf("sleep: %#v", ops[0])
	}
	if ops[1].Kind != "sendLine" || ops[1].Value != "ls" {
		t.Fatalf("send: %#v", ops[1])
	}
	if ops[2].Kind != "waitForPrompt" || ops[2].Timeout != 30*time.Second {
		t.Fatalf("prompt: %#v", ops[2])
	}
	if ops[4].Value != "cd /data/" {
		t.Fatalf("cd: %#v", ops[4])
	}
}

func TestParseRecordedScriptRejectsDialogAPI(t *testing.T) {
	_, err := ParseRecordedScript(`async function main() {
  const sensitiveValue0 = await nct.dialog.prompt("Enter sensitive value", "", { sensitive: true });
  await nct.screen.sendLine(sensitiveValue0, { sensitive: true });
}
await main();`)
	if err == nil || !strings.Contains(err.Error(), "not migrated") {
		t.Fatalf("err=%v", err)
	}
}

func TestParseRecordedScriptRoundTripFromRecorder(t *testing.T) {
	code := StepsToJavaScript([]Step{
		{Type: "sleep", Value: 1500},
		{Type: "send", Value: "ls -la"},
		{Type: "waitForPrompt", TimeoutMs: 30000},
	}, "2026-06-27")
	ops, err := ParseRecordedScript(code)
	if err != nil {
		t.Fatal(err)
	}
	if len(ops) != 3 || ops[1].Value != "ls -la" {
		t.Fatalf("%#v", ops)
	}
}

func TestRunnerWaitForPromptSeesSessionOutput(t *testing.T) {
	wrote := make(chan string, 2)
	runner := NewRunner(func(sessionID string, data []byte) error {
		wrote <- string(data)
		return nil
	})
	go func() {
		time.Sleep(20 * time.Millisecond)
		runner.ObserveOutput("s1", []byte("root@host:/data# "))
	}()
	run, err := runner.Start(StartRunRequest{
		SessionID: "s1",
		Content: `async function main() {
  await nct.screen.sendLine("ls");
  await nct.screen.waitForPrompt(1000);
}
await main();`,
	})
	if err != nil {
		t.Fatal(err)
	}
	deadline := time.Now().Add(time.Second)
	for {
		listed := runner.List("s1")
		if len(listed) == 1 && listed[0].Status == "completed" {
			break
		}
		if time.Now().After(deadline) {
			t.Fatalf("run did not complete: %#v", listed)
		}
		time.Sleep(10 * time.Millisecond)
	}
	if run.RunID == "" {
		t.Fatal("missing run id")
	}
	select {
	case <-wrote:
	case <-time.After(time.Second):
		t.Fatal("sendLine did not write")
	}
}
