// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KnownHostsService exposes the user's system OpenSSH known_hosts files to the
 * renderer so the vault known-hosts page can scan and import them. The
 * application's own pinned keys live in the profile known_hosts file owned by
 * the terminal service; this surface only reads the OS-level files.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ReadKnownHosts returns the concatenated system known_hosts content in the
 * OpenSSH `host key-type base64` line format, or "" when no file exists so
 * the renderer can tell "nothing scanned" from "unavailable".
 * @returns {$CancellablePromise<string>}
 */
export function ReadKnownHosts() {
    return $Call.ByID(1317759653);
}
