// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrayPanelWindowService owns the #/tray panel window lifecycle: lazy
 * creation, the PaintReady show handshake (WebView2 renders nothing while a
 * window is hidden, identical to the settings window), hide-on-close and the
 * show/hide hooks TrayService uses to mirror menu data onto the panel.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Hide hides the panel window; the loaded page is kept for the next open.
 * @returns {$CancellablePromise<boolean>}
 */
export function Hide() {
    return $Call.ByID(2050714135);
}

/**
 * Open shows the tray panel window. If the panel page has not reported its
 * first paint yet, the show is deferred to PaintReady so the user never sees
 * a blank frame.
 * @returns {$CancellablePromise<boolean>}
 */
export function Open() {
    return $Call.ByID(1663989835);
}

/**
 * PaintReady is called by the panel page after its first render
 * (LemonSSHBridge.notifyTrayPanelPaintReady) and completes a pending show.
 * @returns {$CancellablePromise<boolean>}
 */
export function PaintReady() {
    return $Call.ByID(2033287604);
}

/**
 * Preload creates the hidden panel window off the open path so the first
 * open only pays the show, not the WebView bootstrap.
 * @returns {$CancellablePromise<void>}
 */
export function Preload() {
    return $Call.ByID(2139866556);
}
