// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrayService owns the tray context menu and rebuilds it whenever the
 * renderer pushes new tray menu data (sessions / hosts / port-forward rules)
 * or reports a new appearance language.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseSessionFromPanel asks the main-window renderer to close one session.
 * The main window stays where it is: closing a session from the tray panel
 * must not yank focus.
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.trayMenuResult>}
 */
export function CloseSessionFromPanel(sessionID) {
    return $Call.ByID(785851521, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ConnectToHost restores the main window and asks its renderer to open one
 * vault host (the panel's connect action; credential and vault handling stay
 * renderer-side, including the app-lock connect queue).
 * @param {string} hostID
 * @returns {$CancellablePromise<$models.trayMenuResult>}
 */
export function ConnectToHost(hostID) {
    return $Call.ByID(3492252646, hostID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CurrentTrayMenuData reports the latest renderer-pushed menu data (panel
 * bootstrap fallback).
 * @returns {$CancellablePromise<$models.TrayMenuData>}
 */
export function CurrentTrayMenuData() {
    return $Call.ByID(4040840789).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * FocusSession restores the main window and asks its renderer to activate one
 * session. Shared by the tray menu session rows and the panel's jump action
 * path (JumpToSessionFromPanel emits the panel-specific twin event).
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.trayMenuResult>}
 */
export function FocusSession(sessionID) {
    return $Call.ByID(1566210793, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * JumpToSessionFromPanel is the tray panel's jump entry point. It routes the
 * request through the same focus pipeline as FocusSession, emitting the
 * panel-scoped event the main window's tray-panel subscription listens for.
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.trayMenuResult>}
 */
export function JumpToSessionFromPanel(sessionID) {
    return $Call.ByID(3715107962, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenMainWindow restores the main window (close-to-tray / minimised safe).
 * @returns {$CancellablePromise<$models.trayMenuResult>}
 */
export function OpenMainWindow() {
    return $Call.ByID(1308312828).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Quit terminates the application process (not merely hiding the window).
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(3411543682);
}

/**
 * SetLanguage switches the tray menu language and rebuilds it in place.
 * @param {string} language
 * @returns {$CancellablePromise<boolean>}
 */
export function SetLanguage(language) {
    return $Call.ByID(71540681, language);
}

/**
 * TogglePortForward is the one-click rule toggle behind the README's tray
 * port-forwarding promise. A rule with live tunnels is stopped natively via
 * ForwardService.StopByRuleId; starting needs the renderer's vault host
 * resolution and credentials (and honours its app-lock deferral), so the
 * start request is dispatched to the main window whose existing tray
 * toggle handler drives ForwardService.Start.
 * @param {string} ruleID
 * @returns {$CancellablePromise<$models.trayForwardToggleResult>}
 */
export function TogglePortForward(ruleID) {
    return $Call.ByID(4152576159, ruleID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateTrayMenuData stores the renderer-pushed sessions / hosts / forward
 * rules, rebuilds the tray menu and mirrors the snapshot onto the tray panel
 * window. This is the single menu-content mechanism: the renderer re-pushes
 * on session changes, rule start/stops and main-window re-shows, so the menu
 * and the panel always render the same projection.
 * @param {$models.TrayMenuData} data
 * @returns {$CancellablePromise<$models.trayMenuResult>}
 */
export function UpdateTrayMenuData(data) {
    return $Call.ByID(4261521767, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.trayMenuResult.createFrom;
const $$createType1 = $models.TrayMenuData.createFrom;
const $$createType2 = $models.trayForwardToggleResult.createFrom;
