// Command contracts-codegen emits the TypeScript declarations for the base
// shell contracts from the Go source of truth (internal/app/contracts).
//
// Usage:
//
//	go run ./tools/contracts-codegen            # write the generated file
//	go run ./tools/contracts-codegen --check    # fail if the file is stale
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/binaricat/netcatty/internal/app/contracts"
)

const outputPath = "infrastructure/runtime/contracts/generated/contracts.ts"

func main() {
	checkOnly := len(os.Args) == 2 && os.Args[1] == "--check"
	if err := run(checkOnly); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(checkOnly bool) error {
	codes, err := loadErrorCodeLiterals()
	if err != nil {
		return err
	}
	contents := render(codes, contracts.WireTypes())
	if checkOnly {
		existing, err := os.ReadFile(outputPath)
		if err != nil {
			return fmt.Errorf("reading generated file: %w (run: go run ./tools/contracts-codegen)", err)
		}
		if string(existing) != contents {
			return fmt.Errorf("%s is stale; run: go run ./tools/contracts-codegen", outputPath)
		}
		fmt.Println("contracts.ts up to date")
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(outputPath, []byte(contents), 0o644); err != nil {
		return err
	}
	fmt.Printf("Wrote %s\n", outputPath)
	return nil
}

// loadErrorCodeLiterals parses errors.go so the emitted union cannot drift
// from the Go constants.
func loadErrorCodeLiterals() ([]string, error) {
	source, err := os.ReadFile("internal/app/contracts/errors.go")
	if err != nil {
		return nil, err
	}
	fileSet := token.NewFileSet()
	file, err := parser.ParseFile(fileSet, "errors.go", source, 0)
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	literals := []string{}
	ast.Inspect(file, func(node ast.Node) bool {
		declaration, ok := node.(*ast.GenDecl)
		if !ok || declaration.Tok != token.CONST {
			return true
		}
		for _, spec := range declaration.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for _, name := range valueSpec.Names {
				if !strings.HasPrefix(name.Name, "Code") {
					continue
				}
				literal := errorCodeLiteral(name.Name)
				if !seen[literal] {
					seen[literal] = true
					literals = append(literals, literal)
				}
			}
		}
		return true
	})
	if len(literals) == 0 {
		return nil, fmt.Errorf("no error codes found in errors.go")
	}
	sort.Strings(literals)
	return literals, nil
}

func errorCodeLiteral(constName string) string {
	trimmed := strings.TrimPrefix(constName, "Code")
	var builder strings.Builder
	builder.WriteString("netcatty.")
	for index, runeValue := range trimmed {
		if runeValue >= 'A' && runeValue <= 'Z' {
			if index > 0 {
				builder.WriteRune('_')
			}
			builder.WriteRune(runeValue - 'A' + 'a')
			continue
		}
		builder.WriteRune(runeValue)
	}
	return builder.String()
}

func render(errorCodeLiterals []string, wireTypes []any) string {
	var out strings.Builder
	out.WriteString("// GENERATED FILE - DO NOT EDIT.\n")
	out.WriteString("// Generated by tools/contracts-codegen from internal/app/contracts.\n")
	out.WriteString("// Base wire contracts shared by every Netcatty service (P1-03).\n\n")
	out.WriteString("/** Stable, wire-visible error identity. Never rename or reuse a code. */\n")
	out.WriteString("export type ErrorCode =\n")
	for index, literal := range errorCodeLiterals {
		separator := ""
		if index == len(errorCodeLiterals)-1 {
			separator = ";"
		}
		out.WriteString(fmt.Sprintf("  | %q%s\n", literal, separator))
	}
	out.WriteString("\n")
	out.WriteString("/** Structured error envelope crossing shell boundaries. */\n")
	out.WriteString(emitType(reflect.TypeOf(contracts.Error{})))
	out.WriteString("\n")
	for _, wire := range wireTypes {
		switch wire.(type) {
		case contracts.Error:
			continue // already emitted with its doc comment
		default:
			out.WriteString(emitType(reflect.TypeOf(wire)))
			out.WriteString("\n")
		}
	}
	return out.String()
}

func emitType(t reflect.Type) string {
	var out strings.Builder
	out.WriteString(fmt.Sprintf("export interface %s {\n", tsTypeName(t)))
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("json")
		if tag == "-" {
			continue
		}
		name, options, _ := strings.Cut(tag, ",")
		optional := ""
		if strings.Contains(options, "omitempty") {
			optional = "?"
		}
		out.WriteString(fmt.Sprintf("  %s%s: %s;\n", name, optional, tsType(field.Type)))
	}
	out.WriteString("}\n")
	return out.String()
}

// tsTypeName maps Go wire type names onto TypeScript-safe names. `Error` and
// `Request` would shadow the DOM/global TypeScript types.
var tsTypeNames = map[string]string{
	"Error":   "ServiceError",
	"Request": "ServiceRequest",
}

func tsTypeName(t reflect.Type) string {
	if mapped, ok := tsTypeNames[t.Name()]; ok {
		return mapped
	}
	return t.Name()
}

func tsType(t reflect.Type) string {
	switch t.Kind() {
	case reflect.String:
		if t.Name() == "ErrorCode" {
			return "ErrorCode"
		}
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			// []byte marshals to a base64 string on the wire.
			return "string"
		}
		return tsType(t.Elem()) + "[]"
	case reflect.Map:
		return fmt.Sprintf("Record<string, %s>", tsType(t.Elem()))
	case reflect.Pointer:
		return fmt.Sprintf("%s | null", tsType(t.Elem()))
	case reflect.Struct:
		return tsTypeName(t)
	case reflect.Interface:
		return "unknown"
	default:
		panic(fmt.Sprintf("contracts-codegen: unsupported kind %s (%s)", t.Kind(), t))
	}
}
