// Generated by scripts/migration/export-electron-contract-fixtures.mjs.
// This file proves the synthetic events remain assignable to the canonical union.
import type { AgentEvent } from '../../../infrastructure/ai/harness/types';

export const agentEvents = [
  {
    "sessionId": "chat-session-fixture-1",
    "chatSessionId": "chat-session-fixture-1",
    "backend": "catty",
    "timestamp": 1724361600000,
    "turnId": "turn-fixture-1",
    "id": "event-1",
    "type": "turn_start",
    "backendLabel": "catty"
  },
  {
    "sessionId": "chat-session-fixture-1",
    "chatSessionId": "chat-session-fixture-1",
    "backend": "catty",
    "timestamp": 1724361600000,
    "turnId": "turn-fixture-1",
    "id": "event-2",
    "type": "tool_call",
    "toolCallId": "tool-call-fixture-1",
    "toolName": "session_environment",
    "args": {}
  },
  {
    "sessionId": "chat-session-fixture-1",
    "chatSessionId": "chat-session-fixture-1",
    "backend": "catty",
    "timestamp": 1724361600000,
    "turnId": "turn-fixture-1",
    "id": "event-3",
    "type": "tool_result",
    "toolCallId": "tool-call-fixture-1",
    "toolName": "session_environment",
    "result": "{\"ok\":true,\"platform\":\"fixture\"}"
  },
  {
    "sessionId": "chat-session-fixture-1",
    "chatSessionId": "chat-session-fixture-1",
    "backend": "catty",
    "timestamp": 1724361600000,
    "turnId": "turn-fixture-1",
    "id": "event-4",
    "type": "usage",
    "promptTokens": 120,
    "completionTokens": 30,
    "totalTokens": 150,
    "estimated": false
  },
  {
    "sessionId": "chat-session-fixture-1",
    "chatSessionId": "chat-session-fixture-1",
    "backend": "catty",
    "timestamp": 1724361600000,
    "turnId": "turn-fixture-1",
    "id": "event-5",
    "type": "turn_end",
    "reason": "completed"
  }
] satisfies AgentEvent[];
