// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Action is the parsed intent.
 */
export class Action {
    /**
     * Creates a new Action instance.
     * @param {Partial<Action>} [$$source = {}] - The source object to create the Action.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * "ssh" | "telnet"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["username"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Action}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Action(/** @type {Partial<Action>} */($$parsedSource));
    }
}
