// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminaluse$0 from "../terminaluse/models.js";

/**
 * OpenRequest dials (or borrows) a pooled transport for a standalone SFTP
 * session. It embeds the canonical terminaluse.SSHConnectRequest so every
 * shell shares one dial JSON contract.
 */
export class OpenRequest {
    /**
     * Creates a new OpenRequest instance.
     * @param {Partial<OpenRequest>} [$$source = {}] - The source object to create the OpenRequest.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("privateKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["privateKey"] = "";
        }
        if (!("passphrase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["passphrase"] = "";
        }
        if (!("certificate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["certificate"] = "";
        }
        if (!("proxyUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyUrl"] = "";
        }
        if (!("proxyCommand" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyCommand"] = "";
        }
        if (!("enableMfa" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableMfa"] = false;
        }
        if (!("useAgent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useAgent"] = false;
        }
        if (!("identityFilePaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["identityFilePaths"] = [];
        }
        if (!("cols" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }
        if (!("term" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["term"] = "";
        }
        if (!("verifyHostKeys" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["verifyHostKeys"] = null;
        }
        if (!("keepaliveInterval" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["keepaliveInterval"] = null;
        }
        if (!("keepaliveCountMax" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["keepaliveCountMax"] = null;
        }
        if (!("forwardX11" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["forwardX11"] = false;
        }
        if (!("x11Display" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["x11Display"] = "";
        }
        if (!("jumpHosts" in $$source)) {
            /**
             * @member
             * @type {terminaluse$0.SSHConnectRequest[]}
             */
            this["jumpHosts"] = [];
        }
        if (!("sudo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sudo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenRequest}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType0;
        const $$createField20_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identityFilePaths" in $$parsedSource) {
            $$parsedSource["identityFilePaths"] = $$createField11_0($$parsedSource["identityFilePaths"]);
        }
        if ("jumpHosts" in $$parsedSource) {
            $$parsedSource["jumpHosts"] = $$createField20_0($$parsedSource["jumpHosts"]);
        }
        return new OpenRequest(/** @type {Partial<OpenRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = terminaluse$0.SSHConnectRequest.createFrom;
const $$createType2 = $Create.Array($$createType1);
