// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CheckResult is the outcome of one release check. It matches the renderer
 * bridge contract (types/global/lemonssh-bridge-app.d.ts).
 */
export class CheckResult {
    /**
     * Creates a new CheckResult instance.
     * @param {Partial<CheckResult>} [$$source = {}] - The source object to create the CheckResult.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["checking"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["ready"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["downloading"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["releaseNotes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["releaseDate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckResult(/** @type {Partial<CheckResult>} */($$parsedSource));
    }
}

/**
 * DownloadResult is the outcome of a download request. The promise resolves
 * when the download finishes; progress streams through EventDownloadProgress.
 */
export class DownloadResult {
    /**
     * Creates a new DownloadResult instance.
     * @param {Partial<DownloadResult>} [$$source = {}] - The source object to create the DownloadResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadResult(/** @type {Partial<DownloadResult>} */($$parsedSource));
    }
}

/**
 * Status is the update lifecycle state surfaced to the renderer.
 * @readonly
 * @enum {string}
 */
export const Status = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusIdle: "idle",
    StatusAvailable: "available",
    StatusDownloading: "downloading",
    StatusReady: "ready",
    StatusError: "error",
};

/**
 * StatusSnapshot is the renderer-facing state hydration payload.
 */
export class StatusSnapshot {
    /**
     * Creates a new StatusSnapshot instance.
     * @param {Partial<StatusSnapshot>} [$$source = {}] - The source object to create the StatusSnapshot.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = Status.$zero;
        }
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("isChecking" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isChecking"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusSnapshot(/** @type {Partial<StatusSnapshot>} */($$parsedSource));
    }
}
