// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Grant is one stored approval rule, shared shape with
 * electron/shared/permissionGrants.cjs (sanitizePermissionGrants output).
 */
export class Grant {
    /**
     * Creates a new Grant instance.
     * @param {Partial<Grant>} [$$source = {}] - The source object to create the Grant.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("capabilityId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["capabilityId"] = "";
        }
        if (!("sessionPattern" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionPattern"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["commandPattern"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["argsPattern"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["note"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Grant instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Grant}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("argsPattern" in $$parsedSource) {
            $$parsedSource["argsPattern"] = $$createField4_0($$parsedSource["argsPattern"]);
        }
        return new Grant(/** @type {Partial<Grant>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
